//////////////////////////////////////
//
// Graphics .H file for .WL6
// IGRAB-ed on Wed Apr 13 06:58:44 1994
//
//////////////////////////////////////

export enum graphicnums {
  // Lump Start
  H_BJPIC = 3,
  H_CASTLEPIC, // 4
  H_BLAZEPIC, // 5
  H_TOPWINDOWPIC, // 6
  H_LEFTWINDOWPIC, // 7
  H_RIGHTWINDOWPIC, // 8
  H_BOTTOMINFOPIC, // 9
  // Lump Start
  C_OPTIONSPIC, // 10
  C_CURSOR1PIC, // 11
  C_CURSOR2PIC, // 12
  C_NOTSELECTEDPIC, // 13
  C_SELECTEDPIC, // 14
  C_FXTITLEPIC, // 15
  C_DIGITITLEPIC, // 16
  C_MUSICTITLEPIC, // 17
  C_MOUSELBACKPIC, // 18
  C_BABYMODEPIC, // 19
  C_EASYPIC, // 20
  C_NORMALPIC, // 21
  C_HARDPIC, // 22
  C_LOADSAVEDISKPIC, // 23
  C_DISKLOADING1PIC, // 24
  C_DISKLOADING2PIC, // 25
  C_CONTROLPIC, // 26
  C_CUSTOMIZEPIC, // 27
  C_LOADGAMEPIC, // 28
  C_SAVEGAMEPIC, // 29
  C_EPISODE1PIC, // 30
  C_EPISODE2PIC, // 31
  C_EPISODE3PIC, // 32
  C_EPISODE4PIC, // 33
  C_EPISODE5PIC, // 34
  C_EPISODE6PIC, // 35
  C_CODEPIC, // 36
  C_TIMECODEPIC, // 37
  C_LEVELPIC, // 38
  C_NAMEPIC, // 39
  C_SCOREPIC, // 40
  C_JOY1PIC, // 41
  C_JOY2PIC, // 42
  // Lump Start
  L_GUYPIC, // 43
  L_COLONPIC, // 44
  L_NUM0PIC, // 45
  L_NUM1PIC, // 46
  L_NUM2PIC, // 47
  L_NUM3PIC, // 48
  L_NUM4PIC, // 49
  L_NUM5PIC, // 50
  L_NUM6PIC, // 51
  L_NUM7PIC, // 52
  L_NUM8PIC, // 53
  L_NUM9PIC, // 54
  L_PERCENTPIC, // 55
  L_APIC, // 56
  L_BPIC, // 57
  L_CPIC, // 58
  L_DPIC, // 59
  L_EPIC, // 60
  L_FPIC, // 61
  L_GPIC, // 62
  L_HPIC, // 63
  L_IPIC, // 64
  L_JPIC, // 65
  L_KPIC, // 66
  L_LPIC, // 67
  L_MPIC, // 68
  L_NPIC, // 69
  L_OPIC, // 70
  L_PPIC, // 71
  L_QPIC, // 72
  L_RPIC, // 73
  L_SPIC, // 74
  L_TPIC, // 75
  L_UPIC, // 76
  L_VPIC, // 77
  L_WPIC, // 78
  L_XPIC, // 79
  L_YPIC, // 80
  L_ZPIC, // 81
  L_EXPOINTPIC, // 82
  L_APOSTROPHEPIC, // 83
  L_GUY2PIC, // 84
  L_BJWINSPIC, // 85
  STATUSBARPIC, // 86
  TITLEPIC, // 87
  PG13PIC, // 88
  CREDITSPIC, // 89
  HIGHSCORESPIC, // 90
  // Lump Start
  KNIFEPIC, // 91
  GUNPIC, // 92
  MACHINEGUNPIC, // 93
  GATLINGGUNPIC, // 94
  NOKEYPIC, // 95
  GOLDKEYPIC, // 96
  SILVERKEYPIC, // 97
  N_BLANKPIC, // 98
  N_0PIC, // 99
  N_1PIC, // 100
  N_2PIC, // 101
  N_3PIC, // 102
  N_4PIC, // 103
  N_5PIC, // 104
  N_6PIC, // 105
  N_7PIC, // 106
  N_8PIC, // 107
  N_9PIC, // 108
  FACE1APIC, // 109
  FACE1BPIC, // 110
  FACE1CPIC, // 111
  FACE2APIC, // 112
  FACE2BPIC, // 113
  FACE2CPIC, // 114
  FACE3APIC, // 115
  FACE3BPIC, // 116
  FACE3CPIC, // 117
  FACE4APIC, // 118
  FACE4BPIC, // 119
  FACE4CPIC, // 120
  FACE5APIC, // 121
  FACE5BPIC, // 122
  FACE5CPIC, // 123
  FACE6APIC, // 124
  FACE6BPIC, // 125
  FACE6CPIC, // 126
  FACE7APIC, // 127
  FACE7BPIC, // 128
  FACE7CPIC, // 129
  FACE8APIC, // 130
  GOTGATLINGPIC, // 131
  MUTANTBJPIC, // 132
  PAUSEDPIC, // 133
  GETPSYCHEDPIC, // 134

  ORDERSCREEN = 136,
  ERRORSCREEN, // 137
  T_HELPART, // 138
  T_DEMO0, // 139
  T_DEMO1, // 140
  T_DEMO2, // 141
  T_DEMO3, // 142
  T_ENDART1, // 143
  T_ENDART2, // 144
  T_ENDART3, // 145
  T_ENDART4, // 146
  T_ENDART5, // 147
  T_ENDART6, // 148
  ENUMEND,
}

// The original is a plain C enum whose members are used unqualified.
export const {
  H_BJPIC,
  H_CASTLEPIC,
  H_BLAZEPIC,
  H_TOPWINDOWPIC,
  H_LEFTWINDOWPIC,
  H_RIGHTWINDOWPIC,
  H_BOTTOMINFOPIC,
  C_OPTIONSPIC,
  C_CURSOR1PIC,
  C_CURSOR2PIC,
  C_NOTSELECTEDPIC,
  C_SELECTEDPIC,
  C_FXTITLEPIC,
  C_DIGITITLEPIC,
  C_MUSICTITLEPIC,
  C_MOUSELBACKPIC,
  C_BABYMODEPIC,
  C_EASYPIC,
  C_NORMALPIC,
  C_HARDPIC,
  C_LOADSAVEDISKPIC,
  C_DISKLOADING1PIC,
  C_DISKLOADING2PIC,
  C_CONTROLPIC,
  C_CUSTOMIZEPIC,
  C_LOADGAMEPIC,
  C_SAVEGAMEPIC,
  C_EPISODE1PIC,
  C_EPISODE2PIC,
  C_EPISODE3PIC,
  C_EPISODE4PIC,
  C_EPISODE5PIC,
  C_EPISODE6PIC,
  C_CODEPIC,
  C_TIMECODEPIC,
  C_LEVELPIC,
  C_NAMEPIC,
  C_SCOREPIC,
  C_JOY1PIC,
  C_JOY2PIC,
  L_GUYPIC,
  L_COLONPIC,
  L_NUM0PIC,
  L_NUM1PIC,
  L_NUM2PIC,
  L_NUM3PIC,
  L_NUM4PIC,
  L_NUM5PIC,
  L_NUM6PIC,
  L_NUM7PIC,
  L_NUM8PIC,
  L_NUM9PIC,
  L_PERCENTPIC,
  L_APIC,
  L_BPIC,
  L_CPIC,
  L_DPIC,
  L_EPIC,
  L_FPIC,
  L_GPIC,
  L_HPIC,
  L_IPIC,
  L_JPIC,
  L_KPIC,
  L_LPIC,
  L_MPIC,
  L_NPIC,
  L_OPIC,
  L_PPIC,
  L_QPIC,
  L_RPIC,
  L_SPIC,
  L_TPIC,
  L_UPIC,
  L_VPIC,
  L_WPIC,
  L_XPIC,
  L_YPIC,
  L_ZPIC,
  L_EXPOINTPIC,
  L_APOSTROPHEPIC,
  L_GUY2PIC,
  L_BJWINSPIC,
  STATUSBARPIC,
  TITLEPIC,
  PG13PIC,
  CREDITSPIC,
  HIGHSCORESPIC,
  KNIFEPIC,
  GUNPIC,
  MACHINEGUNPIC,
  GATLINGGUNPIC,
  NOKEYPIC,
  GOLDKEYPIC,
  SILVERKEYPIC,
  N_BLANKPIC,
  N_0PIC,
  N_1PIC,
  N_2PIC,
  N_3PIC,
  N_4PIC,
  N_5PIC,
  N_6PIC,
  N_7PIC,
  N_8PIC,
  N_9PIC,
  FACE1APIC,
  FACE1BPIC,
  FACE1CPIC,
  FACE2APIC,
  FACE2BPIC,
  FACE2CPIC,
  FACE3APIC,
  FACE3BPIC,
  FACE3CPIC,
  FACE4APIC,
  FACE4BPIC,
  FACE4CPIC,
  FACE5APIC,
  FACE5BPIC,
  FACE5CPIC,
  FACE6APIC,
  FACE6BPIC,
  FACE6CPIC,
  FACE7APIC,
  FACE7BPIC,
  FACE7CPIC,
  FACE8APIC,
  GOTGATLINGPIC,
  MUTANTBJPIC,
  PAUSEDPIC,
  GETPSYCHEDPIC,
  ORDERSCREEN,
  ERRORSCREEN,
  T_HELPART,
  T_DEMO0,
  T_DEMO1,
  T_DEMO2,
  T_DEMO3,
  T_ENDART1,
  T_ENDART2,
  T_ENDART3,
  T_ENDART4,
  T_ENDART5,
  T_ENDART6,
  ENUMEND,
} = graphicnums;

//
// Data LUMPs
//
export const README_LUMP_START = 3;
export const README_LUMP_END = 9;

export const CONTROLS_LUMP_START = 10;
export const CONTROLS_LUMP_END = 42;

export const LEVELEND_LUMP_START = 43;
export const LEVELEND_LUMP_END = 85;

export const LATCHPICS_LUMP_START = 91;
export const LATCHPICS_LUMP_END = 134;

//
// Amount of each data item
//
export const NUMCHUNKS = 149;
export const NUMFONT = 2;
export const NUMFONTM = 0;
export const NUMPICS = 132;
export const NUMPICM = 0;
export const NUMSPRITES = 0;
export const NUMTILE8 = 72;
export const NUMTILE8M = 0;
export const NUMTILE16 = 0;
export const NUMTILE16M = 0;
export const NUMTILE32 = 0;
export const NUMTILE32M = 0;
export const NUMEXTERNS = 13;
//
// File offsets for data items
//
export const STRUCTPIC = 0;

export const STARTFONT = 1;
export const STARTFONTM = 3;
export const STARTPICS = 3;
export const STARTPICM = 135;
export const STARTSPRITES = 135;
export const STARTTILE8 = 135;
export const STARTTILE8M = 136;
export const STARTTILE16 = 136;
export const STARTTILE16M = 136;
export const STARTTILE32 = 136;
export const STARTTILE32M = 136;
export const STARTEXTERNS = 136;

//
// Thank you for using IGRAB!
//
