// @generated by oracle/generate-dgroup-layout.mjs
// Do not edit by hand; regenerate after oracle MAP / locked binary changes.

export const DGROUP_LAYOUT = {
  "generatedBy": "oracle/generate-dgroup-layout.mjs",
  "generatedAt": "not-recorded-for-reproducible-output",
  "status": "rebuild-map-derived; retail EXE is locked and decompressed, but retail DGROUP symbol equality still requires instrumented/extracted confirmation",
  "sourceMap": {
    "path": "source/WOLFSRC/WOLF3D.MAP",
    "sha256": "1a14d6d4c61c714cca5ed0467cb8ae9754bf472edfd8a79e5b4a84e9bfe2a016",
    "note": "Checked-in Borland debug MAP; offsets are strong rebuild evidence, not yet retail-authoritative."
  },
  "retailExe": {
    "path": "steam/base/wolf3d.exe",
    "sha256": "48d9594649f330956e86ea1892bab76b2d83cfd4038e262ff8f3383ba945ec09",
    "packedBytes": 108779,
    "decompressedBytes": 254014,
    "sanityStrings": {
      "Wolfenstein": true,
      "Episode": true,
      "VSWAP": true
    }
  },
  "dgroup": {
    "segment": "0x3A39",
    "linear": "0x3A390",
    "dataStart": "0x3A390",
    "bssEnd": "0x49340",
    "segments": [
      {
        "name": "_DATA",
        "className": "DATA",
        "start": "0x3A390",
        "stop": "0x3EAC9",
        "length": "0x0473A"
      },
      {
        "name": "_CVTSEG",
        "className": "DATA",
        "start": "0x3EACA",
        "stop": "0x3EACD",
        "length": "0x00004"
      },
      {
        "name": "_SCNSEG",
        "className": "DATA",
        "start": "0x3EACE",
        "stop": "0x3EAD9",
        "length": "0x0000C"
      },
      {
        "name": "_CONST",
        "className": "CONST",
        "start": "0x3EADA",
        "stop": "0x3EADA",
        "length": "0x00000"
      },
      {
        "name": "_INIT_",
        "className": "INITDATA",
        "start": "0x3EADA",
        "stop": "0x3EAF7",
        "length": "0x0001E"
      },
      {
        "name": "_INITEND_",
        "className": "INITDATA",
        "start": "0x3EAF8",
        "stop": "0x3EAF8",
        "length": "0x00000"
      },
      {
        "name": "_EXIT_",
        "className": "EXITDATA",
        "start": "0x3EAF8",
        "stop": "0x3EAFD",
        "length": "0x00006"
      },
      {
        "name": "_EXITEND_",
        "className": "EXITDATA",
        "start": "0x3EAFE",
        "stop": "0x3EAFE",
        "length": "0x00000"
      },
      {
        "name": "_BSS",
        "className": "BSS",
        "start": "0x3EAFE",
        "stop": "0x3ED73",
        "length": "0x00276"
      },
      {
        "name": "_COMDEF_",
        "className": "BSS",
        "start": "0x3ED74",
        "stop": "0x4933E",
        "length": "0x0A5CB"
      },
      {
        "name": "_BSSEND",
        "className": "BSSEND",
        "start": "0x4933F",
        "stop": "0x4933F",
        "length": "0x00000"
      }
    ]
  },
  "farBss": {
    "segments": [
      {
        "name": "_FARBSS",
        "className": "FAR_BSS",
        "start": "0x33DA0",
        "stop": "0x33DA0",
        "length": "0x00000"
      },
      {
        "name": "_COMDEF_AA_",
        "className": "FAR_BSS",
        "start": "0x33DA0",
        "stop": "0x342F8",
        "length": "0x00559"
      },
      {
        "name": "_COMDEF_AB_",
        "className": "FAR_BSS",
        "start": "0x34300",
        "stop": "0x34A07",
        "length": "0x00708"
      },
      {
        "name": "_COMDEF_AC_",
        "className": "FAR_BSS",
        "start": "0x34A10",
        "stop": "0x3581F",
        "length": "0x00E10"
      },
      {
        "name": "_COMDEF_AD_",
        "className": "FAR_BSS",
        "start": "0x35820",
        "stop": "0x358B4",
        "length": "0x00095"
      },
      {
        "name": "_COMDEF_AE_",
        "className": "FAR_BSS",
        "start": "0x358C0",
        "stop": "0x36ABF",
        "length": "0x01200"
      },
      {
        "name": "_COMDEF_AF_",
        "className": "FAR_BSS",
        "start": "0x36AC0",
        "stop": "0x37CBF",
        "length": "0x01200"
      },
      {
        "name": "_COMDEF_AG_",
        "className": "FAR_BSS",
        "start": "0x37CC0",
        "stop": "0x39D8F",
        "length": "0x020D0"
      },
      {
        "name": "_COMDEF_AH_",
        "className": "FAR_BSS",
        "start": "0x39D90",
        "stop": "0x3A08F",
        "length": "0x00300"
      },
      {
        "name": "_COMDEF_AI_",
        "className": "FAR_BSS",
        "start": "0x3A090",
        "stop": "0x3A38F",
        "length": "0x00300"
      }
    ]
  },
  "structLayouts": {
    "statetype": {
      "bytes": 16,
      "fields": [
        [
          "rotate",
          0,
          2,
          "boolean enum"
        ],
        [
          "shapenum",
          2,
          2,
          "int"
        ],
        [
          "tictime",
          4,
          2,
          "int"
        ],
        [
          "think",
          6,
          4,
          "medium-model code pointer"
        ],
        [
          "action",
          10,
          4,
          "medium-model code pointer"
        ],
        [
          "next",
          14,
          2,
          "near data pointer"
        ]
      ]
    },
    "statobj_t": {
      "bytes": 8,
      "fields": [
        [
          "tilex",
          0,
          1,
          "byte"
        ],
        [
          "tiley",
          1,
          1,
          "byte"
        ],
        [
          "visspot",
          2,
          2,
          "near byte pointer"
        ],
        [
          "shapenum",
          4,
          2,
          "int"
        ],
        [
          "flags",
          6,
          1,
          "byte"
        ],
        [
          "itemnumber",
          7,
          1,
          "byte"
        ]
      ]
    },
    "doorobj_t": {
      "bytes": 10,
      "fields": [
        [
          "tilex",
          0,
          1,
          "byte"
        ],
        [
          "tiley",
          1,
          1,
          "byte"
        ],
        [
          "vertical",
          2,
          2,
          "boolean enum"
        ],
        [
          "lock",
          4,
          1,
          "byte"
        ],
        [
          "padding",
          5,
          1,
          "word alignment"
        ],
        [
          "action",
          6,
          2,
          "enum"
        ],
        [
          "ticcount",
          8,
          2,
          "int"
        ]
      ]
    },
    "objtype": {
      "bytes": 60,
      "fields": [
        [
          "active",
          0,
          2,
          "activetype enum"
        ],
        [
          "ticcount",
          2,
          2,
          "int"
        ],
        [
          "obclass",
          4,
          2,
          "classtype enum"
        ],
        [
          "state",
          6,
          2,
          "near statetype pointer"
        ],
        [
          "flags",
          8,
          1,
          "byte"
        ],
        [
          "padding",
          9,
          1,
          "word alignment"
        ],
        [
          "distance",
          10,
          4,
          "long"
        ],
        [
          "dir",
          14,
          2,
          "dirtype enum"
        ],
        [
          "x",
          16,
          4,
          "fixed long"
        ],
        [
          "y",
          20,
          4,
          "fixed long"
        ],
        [
          "tilex",
          24,
          2,
          "unsigned"
        ],
        [
          "tiley",
          26,
          2,
          "unsigned"
        ],
        [
          "areanumber",
          28,
          1,
          "byte"
        ],
        [
          "padding",
          29,
          1,
          "word alignment"
        ],
        [
          "viewx",
          30,
          2,
          "int"
        ],
        [
          "viewheight",
          32,
          2,
          "unsigned"
        ],
        [
          "transx",
          34,
          4,
          "fixed long"
        ],
        [
          "transy",
          38,
          4,
          "fixed long"
        ],
        [
          "angle",
          42,
          2,
          "int"
        ],
        [
          "hitpoints",
          44,
          2,
          "int"
        ],
        [
          "speed",
          46,
          4,
          "long"
        ],
        [
          "temp1",
          50,
          2,
          "int"
        ],
        [
          "temp2",
          52,
          2,
          "int"
        ],
        [
          "temp3",
          54,
          2,
          "int"
        ],
        [
          "next",
          56,
          2,
          "near objstruct pointer"
        ],
        [
          "prev",
          58,
          2,
          "near objstruct pointer"
        ]
      ]
    },
    "gametype": {
      "bytes": 66,
      "fields": [
        [
          "difficulty",
          0,
          2,
          "int"
        ],
        [
          "mapon",
          2,
          2,
          "int"
        ],
        [
          "oldscore",
          4,
          4,
          "long"
        ],
        [
          "score",
          8,
          4,
          "long"
        ],
        [
          "nextextra",
          12,
          4,
          "long"
        ],
        [
          "lives",
          16,
          2,
          "int"
        ],
        [
          "health",
          18,
          2,
          "int"
        ],
        [
          "ammo",
          20,
          2,
          "int"
        ],
        [
          "keys",
          22,
          2,
          "int"
        ],
        [
          "bestweapon",
          24,
          2,
          "weapontype enum"
        ],
        [
          "weapon",
          26,
          2,
          "weapontype enum"
        ],
        [
          "chosenweapon",
          28,
          2,
          "weapontype enum"
        ],
        [
          "faceframe",
          30,
          2,
          "int"
        ],
        [
          "attackframe",
          32,
          2,
          "int"
        ],
        [
          "attackcount",
          34,
          2,
          "int"
        ],
        [
          "weaponframe",
          36,
          2,
          "int"
        ],
        [
          "episode",
          38,
          2,
          "int"
        ],
        [
          "secretcount",
          40,
          2,
          "int"
        ],
        [
          "treasurecount",
          42,
          2,
          "int"
        ],
        [
          "killcount",
          44,
          2,
          "int"
        ],
        [
          "secrettotal",
          46,
          2,
          "int"
        ],
        [
          "treasuretotal",
          48,
          2,
          "int"
        ],
        [
          "killtotal",
          50,
          2,
          "int"
        ],
        [
          "TimeCount",
          52,
          4,
          "long"
        ],
        [
          "killx",
          56,
          4,
          "long"
        ],
        [
          "killy",
          60,
          4,
          "long"
        ],
        [
          "victoryflag",
          64,
          2,
          "boolean enum"
        ]
      ]
    },
    "LRstruct": {
      "bytes": 10,
      "fields": [
        [
          "kill",
          0,
          2,
          "int"
        ],
        [
          "secret",
          2,
          2,
          "int"
        ],
        [
          "treasure",
          4,
          2,
          "int"
        ],
        [
          "time",
          6,
          4,
          "long"
        ]
      ]
    }
  },
  "saveRecords": [
    {
      "name": "gamestate",
      "symbol": "_gamestate",
      "bytes": 66,
      "checksum": true,
      "source": "WL_MAIN.C SaveTheGame",
      "symbolInfo": {
        "name": "_gamestate",
        "segment": "0x3A39",
        "offset": "0x95C2",
        "linear": "0x43952",
        "nearOffset": "0x95C2"
      }
    },
    {
      "name": "LevelRatios",
      "symbol": "_LevelRatios",
      "bytes": 80,
      "checksum": true,
      "source": "LRstruct[8]",
      "symbolInfo": {
        "name": "_LevelRatios",
        "segment": "0x3A39",
        "offset": "0x9906",
        "linear": "0x43C96",
        "nearOffset": "0x9906"
      }
    },
    {
      "name": "tilemap",
      "symbol": "_tilemap",
      "bytes": 4096,
      "checksum": true,
      "source": "byte[64][64]",
      "symbolInfo": {
        "name": "_tilemap",
        "segment": "0x3A39",
        "offset": "0x75BA",
        "linear": "0x4194A",
        "nearOffset": "0x75BA"
      }
    },
    {
      "name": "actorat",
      "symbol": "_actorat",
      "bytes": 8192,
      "checksum": true,
      "source": "near pointer[64][64]",
      "symbolInfo": {
        "name": "_actorat",
        "segment": "0x3A39",
        "offset": "0x55BA",
        "linear": "0x3F94A",
        "nearOffset": "0x55BA"
      }
    },
    {
      "name": "areaconnect",
      "symbol": "_areaconnect",
      "bytes": 1369,
      "checksum": false,
      "source": "byte far[37][37]",
      "symbolInfo": {
        "name": "_areaconnect",
        "segment": "0x33DA",
        "offset": "0x0000",
        "linear": "0x33DA0",
        "nearOffset": "0x0000"
      }
    },
    {
      "name": "areabyplayer",
      "symbol": "_areabyplayer",
      "bytes": 74,
      "checksum": false,
      "source": "boolean[37]",
      "symbolInfo": {
        "name": "_areabyplayer",
        "segment": "0x3A39",
        "offset": "0x52DC",
        "linear": "0x3F66C",
        "nearOffset": "0x52DC"
      }
    },
    {
      "name": "objlistRecords",
      "symbol": "_objlist",
      "bytes": "dynamic:activeActors*60 + nullobj(60)",
      "checksum": false,
      "source": "objtype linked list",
      "symbolInfo": {
        "name": "_objlist",
        "segment": "0x3A39",
        "offset": "0xB51C",
        "linear": "0x458AC",
        "nearOffset": "0xB51C"
      }
    },
    {
      "name": "laststatobj",
      "symbol": "_laststatobj",
      "bytes": 2,
      "checksum": true,
      "source": "near pointer",
      "symbolInfo": {
        "name": "_laststatobj",
        "segment": "0x3A39",
        "offset": "0x893A",
        "linear": "0x42CCA",
        "nearOffset": "0x893A"
      }
    },
    {
      "name": "statobjlist",
      "symbol": "_statobjlist",
      "bytes": 3200,
      "checksum": true,
      "source": "statobj_t[400]",
      "symbolInfo": {
        "name": "_statobjlist",
        "segment": "0x3A39",
        "offset": "0x893C",
        "linear": "0x42CCC",
        "nearOffset": "0x893C"
      }
    },
    {
      "name": "doorposition",
      "symbol": "_doorposition",
      "bytes": 128,
      "checksum": true,
      "source": "unsigned[64]",
      "symbolInfo": {
        "name": "_doorposition",
        "segment": "0x3A39",
        "offset": "0x5328",
        "linear": "0x3F6B8",
        "nearOffset": "0x5328"
      }
    },
    {
      "name": "doorobjlist",
      "symbol": "_doorobjlist",
      "bytes": 640,
      "checksum": true,
      "source": "doorobj_t[64]",
      "symbolInfo": {
        "name": "_doorobjlist",
        "segment": "0x3A39",
        "offset": "0x86BA",
        "linear": "0x42A4A",
        "nearOffset": "0x86BA"
      }
    },
    {
      "name": "pwallstate",
      "symbol": "_pwallstate",
      "bytes": 2,
      "checksum": true,
      "source": "unsigned",
      "symbolInfo": {
        "name": "_pwallstate",
        "segment": "0x3A39",
        "offset": "0x5326",
        "linear": "0x3F6B6",
        "nearOffset": "0x5326"
      }
    },
    {
      "name": "pwallx",
      "symbol": "_pwallx",
      "bytes": 2,
      "checksum": true,
      "source": "unsigned",
      "symbolInfo": {
        "name": "_pwallx",
        "segment": "0x3A39",
        "offset": "0x52DA",
        "linear": "0x3F66A",
        "nearOffset": "0x52DA"
      }
    },
    {
      "name": "pwally",
      "symbol": "_pwally",
      "bytes": 2,
      "checksum": true,
      "source": "unsigned",
      "symbolInfo": {
        "name": "_pwally",
        "segment": "0x3A39",
        "offset": "0x52D8",
        "linear": "0x3F668",
        "nearOffset": "0x52D8"
      }
    },
    {
      "name": "pwalldir",
      "symbol": "_pwalldir",
      "bytes": 2,
      "checksum": true,
      "source": "int",
      "symbolInfo": {
        "name": "_pwalldir",
        "segment": "0x3A39",
        "offset": "0x52D6",
        "linear": "0x3F666",
        "nearOffset": "0x52D6"
      }
    },
    {
      "name": "pwallpos",
      "symbol": "_pwallpos",
      "bytes": 2,
      "checksum": true,
      "source": "unsigned",
      "symbolInfo": {
        "name": "_pwallpos",
        "segment": "0x3A39",
        "offset": "0x53A8",
        "linear": "0x3F738",
        "nearOffset": "0x53A8"
      }
    },
    {
      "name": "checksum",
      "symbol": null,
      "bytes": 4,
      "checksum": false,
      "source": "trailing long",
      "symbolInfo": null
    }
  ],
  "saveCriticalSymbols": {
    "_gamestate": {
      "name": "_gamestate",
      "segment": "0x3A39",
      "offset": "0x95C2",
      "linear": "0x43952",
      "nearOffset": "0x95C2"
    },
    "_LevelRatios": {
      "name": "_LevelRatios",
      "segment": "0x3A39",
      "offset": "0x9906",
      "linear": "0x43C96",
      "nearOffset": "0x9906"
    },
    "_tilemap": {
      "name": "_tilemap",
      "segment": "0x3A39",
      "offset": "0x75BA",
      "linear": "0x4194A",
      "nearOffset": "0x75BA"
    },
    "_actorat": {
      "name": "_actorat",
      "segment": "0x3A39",
      "offset": "0x55BA",
      "linear": "0x3F94A",
      "nearOffset": "0x55BA"
    },
    "_areaconnect": {
      "name": "_areaconnect",
      "segment": "0x33DA",
      "offset": "0x0000",
      "linear": "0x33DA0",
      "nearOffset": "0x0000"
    },
    "_areabyplayer": {
      "name": "_areabyplayer",
      "segment": "0x3A39",
      "offset": "0x52DC",
      "linear": "0x3F66C",
      "nearOffset": "0x52DC"
    },
    "_objlist": {
      "name": "_objlist",
      "segment": "0x3A39",
      "offset": "0xB51C",
      "linear": "0x458AC",
      "nearOffset": "0xB51C"
    },
    "_player": {
      "name": "_player",
      "segment": "0x3A39",
      "offset": "0x95BC",
      "linear": "0x4394C",
      "nearOffset": "0x95BC"
    },
    "_new": {
      "name": "_new",
      "segment": "0x3A39",
      "offset": "0x95BE",
      "linear": "0x4394E",
      "nearOffset": "0x95BE"
    },
    "_obj": {
      "name": "_obj",
      "segment": "0x3A39",
      "offset": "0xB51A",
      "linear": "0x458AA",
      "nearOffset": "0xB51A"
    },
    "_lastobj": {
      "name": "_lastobj",
      "segment": "0x3A39",
      "offset": "0xB518",
      "linear": "0x458A8",
      "nearOffset": "0xB518"
    },
    "_objfreelist": {
      "name": "_objfreelist",
      "segment": "0x3A39",
      "offset": "0xB516",
      "linear": "0x458A6",
      "nearOffset": "0xB516"
    },
    "_laststatobj": {
      "name": "_laststatobj",
      "segment": "0x3A39",
      "offset": "0x893A",
      "linear": "0x42CCA",
      "nearOffset": "0x893A"
    },
    "_statobjlist": {
      "name": "_statobjlist",
      "segment": "0x3A39",
      "offset": "0x893C",
      "linear": "0x42CCC",
      "nearOffset": "0x893C"
    },
    "_doorposition": {
      "name": "_doorposition",
      "segment": "0x3A39",
      "offset": "0x5328",
      "linear": "0x3F6B8",
      "nearOffset": "0x5328"
    },
    "_doorobjlist": {
      "name": "_doorobjlist",
      "segment": "0x3A39",
      "offset": "0x86BA",
      "linear": "0x42A4A",
      "nearOffset": "0x86BA"
    },
    "_lastdoorobj": {
      "name": "_lastdoorobj",
      "segment": "0x3A39",
      "offset": "0xE011",
      "linear": "0x483A1",
      "nearOffset": "0xE011"
    },
    "_pwallstate": {
      "name": "_pwallstate",
      "segment": "0x3A39",
      "offset": "0x5326",
      "linear": "0x3F6B6",
      "nearOffset": "0x5326"
    },
    "_pwallx": {
      "name": "_pwallx",
      "segment": "0x3A39",
      "offset": "0x52DA",
      "linear": "0x3F66A",
      "nearOffset": "0x52DA"
    },
    "_pwally": {
      "name": "_pwally",
      "segment": "0x3A39",
      "offset": "0x52D8",
      "linear": "0x3F668",
      "nearOffset": "0x52D8"
    },
    "_pwalldir": {
      "name": "_pwalldir",
      "segment": "0x3A39",
      "offset": "0x52D6",
      "linear": "0x3F666",
      "nearOffset": "0x52D6"
    },
    "_pwallpos": {
      "name": "_pwallpos",
      "segment": "0x3A39",
      "offset": "0x53A8",
      "linear": "0x3F738",
      "nearOffset": "0x53A8"
    }
  },
  "runtimeSymbols": {
    "_gamestate": {
      "name": "_gamestate",
      "segment": "0x3A39",
      "offset": "0x95C2",
      "linear": "0x43952",
      "nearOffset": "0x95C2"
    },
    "_LevelRatios": {
      "name": "_LevelRatios",
      "segment": "0x3A39",
      "offset": "0x9906",
      "linear": "0x43C96",
      "nearOffset": "0x9906"
    },
    "_tilemap": {
      "name": "_tilemap",
      "segment": "0x3A39",
      "offset": "0x75BA",
      "linear": "0x4194A",
      "nearOffset": "0x75BA"
    },
    "_actorat": {
      "name": "_actorat",
      "segment": "0x3A39",
      "offset": "0x55BA",
      "linear": "0x3F94A",
      "nearOffset": "0x55BA"
    },
    "_areaconnect": {
      "name": "_areaconnect",
      "segment": "0x33DA",
      "offset": "0x0000",
      "linear": "0x33DA0",
      "nearOffset": "0x0000"
    },
    "_areabyplayer": {
      "name": "_areabyplayer",
      "segment": "0x3A39",
      "offset": "0x52DC",
      "linear": "0x3F66C",
      "nearOffset": "0x52DC"
    },
    "_objlist": {
      "name": "_objlist",
      "segment": "0x3A39",
      "offset": "0xB51C",
      "linear": "0x458AC",
      "nearOffset": "0xB51C"
    },
    "_player": {
      "name": "_player",
      "segment": "0x3A39",
      "offset": "0x95BC",
      "linear": "0x4394C",
      "nearOffset": "0x95BC"
    },
    "_new": {
      "name": "_new",
      "segment": "0x3A39",
      "offset": "0x95BE",
      "linear": "0x4394E",
      "nearOffset": "0x95BE"
    },
    "_obj": {
      "name": "_obj",
      "segment": "0x3A39",
      "offset": "0xB51A",
      "linear": "0x458AA",
      "nearOffset": "0xB51A"
    },
    "_lastobj": {
      "name": "_lastobj",
      "segment": "0x3A39",
      "offset": "0xB518",
      "linear": "0x458A8",
      "nearOffset": "0xB518"
    },
    "_objfreelist": {
      "name": "_objfreelist",
      "segment": "0x3A39",
      "offset": "0xB516",
      "linear": "0x458A6",
      "nearOffset": "0xB516"
    },
    "_laststatobj": {
      "name": "_laststatobj",
      "segment": "0x3A39",
      "offset": "0x893A",
      "linear": "0x42CCA",
      "nearOffset": "0x893A"
    },
    "_statobjlist": {
      "name": "_statobjlist",
      "segment": "0x3A39",
      "offset": "0x893C",
      "linear": "0x42CCC",
      "nearOffset": "0x893C"
    },
    "_doorposition": {
      "name": "_doorposition",
      "segment": "0x3A39",
      "offset": "0x5328",
      "linear": "0x3F6B8",
      "nearOffset": "0x5328"
    },
    "_doorobjlist": {
      "name": "_doorobjlist",
      "segment": "0x3A39",
      "offset": "0x86BA",
      "linear": "0x42A4A",
      "nearOffset": "0x86BA"
    },
    "_lastdoorobj": {
      "name": "_lastdoorobj",
      "segment": "0x3A39",
      "offset": "0xE011",
      "linear": "0x483A1",
      "nearOffset": "0xE011"
    },
    "_pwallstate": {
      "name": "_pwallstate",
      "segment": "0x3A39",
      "offset": "0x5326",
      "linear": "0x3F6B6",
      "nearOffset": "0x5326"
    },
    "_pwallx": {
      "name": "_pwallx",
      "segment": "0x3A39",
      "offset": "0x52DA",
      "linear": "0x3F66A",
      "nearOffset": "0x52DA"
    },
    "_pwally": {
      "name": "_pwally",
      "segment": "0x3A39",
      "offset": "0x52D8",
      "linear": "0x3F668",
      "nearOffset": "0x52D8"
    },
    "_pwalldir": {
      "name": "_pwalldir",
      "segment": "0x3A39",
      "offset": "0x52D6",
      "linear": "0x3F666",
      "nearOffset": "0x52D6"
    },
    "_pwallpos": {
      "name": "_pwallpos",
      "segment": "0x3A39",
      "offset": "0x53A8",
      "linear": "0x3F738",
      "nearOffset": "0x53A8"
    },
    "_objcount": {
      "name": "_objcount",
      "segment": "0x3A39",
      "offset": "0xA420",
      "linear": "0x447B0",
      "nearOffset": "0xA420"
    },
    "_doornum": {
      "name": "_doornum",
      "segment": "0x3A39",
      "offset": "0xD85C",
      "linear": "0x47BEC",
      "nearOffset": "0xD85C"
    },
    "_spotvis": {
      "name": "_spotvis",
      "segment": "0x3A39",
      "offset": "0xA516",
      "linear": "0x448A6",
      "nearOffset": "0xA516"
    },
    "_playstate": {
      "name": "_playstate",
      "segment": "0x3A39",
      "offset": "0x95C0",
      "linear": "0x43950",
      "nearOffset": "0x95C0"
    },
    "_killerobj": {
      "name": "_killerobj",
      "segment": "0x3A39",
      "offset": "0xA2BA",
      "linear": "0x4464A",
      "nearOffset": "0xA2BA"
    },
    "_palshifted": {
      "name": "_palshifted",
      "segment": "0x3A39",
      "offset": "0xA41A",
      "linear": "0x447AA",
      "nearOffset": "0xA41A"
    },
    "_bonuscount": {
      "name": "_bonuscount",
      "segment": "0x3A39",
      "offset": "0xA41C",
      "linear": "0x447AC",
      "nearOffset": "0xA41C"
    },
    "_damagecount": {
      "name": "_damagecount",
      "segment": "0x3A39",
      "offset": "0xA41E",
      "linear": "0x447AE",
      "nearOffset": "0xA41E"
    },
    "_godmode": {
      "name": "_godmode",
      "segment": "0x3A39",
      "offset": "0xA512",
      "linear": "0x448A2",
      "nearOffset": "0xA512"
    },
    "_noclip": {
      "name": "_noclip",
      "segment": "0x3A39",
      "offset": "0xA510",
      "linear": "0x448A0",
      "nearOffset": "0xA510"
    },
    "_LastAttacker": {
      "name": "_LastAttacker",
      "segment": "0x3A39",
      "offset": "0xE009",
      "linear": "0x48399",
      "nearOffset": "0xE009"
    },
    "_mapwidth": {
      "name": "_mapwidth",
      "segment": "0x3A39",
      "offset": "0xA2CE",
      "linear": "0x4465E",
      "nearOffset": "0xA2CE"
    },
    "_mapheight": {
      "name": "_mapheight",
      "segment": "0x3A39",
      "offset": "0xA2CC",
      "linear": "0x4465C",
      "nearOffset": "0xA2CC"
    },
    "_tics": {
      "name": "_tics",
      "segment": "0x3A39",
      "offset": "0xA2CA",
      "linear": "0x4465A",
      "nearOffset": "0xA2CA"
    },
    "_thrustspeed": {
      "name": "_thrustspeed",
      "segment": "0x3A39",
      "offset": "0xE00D",
      "linear": "0x4839D",
      "nearOffset": "0xE00D"
    },
    "_anglefrac": {
      "name": "_anglefrac",
      "segment": "0x3A39",
      "offset": "0xA4E2",
      "linear": "0x44872",
      "nearOffset": "0xA4E2"
    },
    "_playerxmove": {
      "name": "_playerxmove",
      "segment": "0x3A39",
      "offset": "0xE005",
      "linear": "0x48395",
      "nearOffset": "0xE005"
    },
    "_playerymove": {
      "name": "_playerymove",
      "segment": "0x3A39",
      "offset": "0xE001",
      "linear": "0x48391",
      "nearOffset": "0xE001"
    },
    "_buttonstate": {
      "name": "_buttonstate",
      "segment": "0x3A39",
      "offset": "0xA4EA",
      "linear": "0x4487A",
      "nearOffset": "0xA4EA"
    },
    "_buttonheld": {
      "name": "_buttonheld",
      "segment": "0x3A39",
      "offset": "0xA4FE",
      "linear": "0x4488E",
      "nearOffset": "0xA4FE"
    },
    "_controlx": {
      "name": "_controlx",
      "segment": "0x3A39",
      "offset": "0xA4FC",
      "linear": "0x4488C",
      "nearOffset": "0xA4FC"
    },
    "_controly": {
      "name": "_controly",
      "segment": "0x3A39",
      "offset": "0xA4FA",
      "linear": "0x4488A",
      "nearOffset": "0xA4FA"
    },
    "_madenoise": {
      "name": "_madenoise",
      "segment": "0x3A39",
      "offset": "0xD844",
      "linear": "0x47BD4",
      "nearOffset": "0xD844"
    },
    "_plux": {
      "name": "_plux",
      "segment": "0x3A39",
      "offset": "0xDFFF",
      "linear": "0x4838F",
      "nearOffset": "0xDFFF"
    },
    "_pluy": {
      "name": "_pluy",
      "segment": "0x3A39",
      "offset": "0xDFFD",
      "linear": "0x4838D",
      "nearOffset": "0xDFFD"
    },
    "_centerx": {
      "name": "_centerx",
      "segment": "0x3A39",
      "offset": "0x9896",
      "linear": "0x43C26",
      "nearOffset": "0x9896"
    },
    "_shootdelta": {
      "name": "_shootdelta",
      "segment": "0x3A39",
      "offset": "0x9894",
      "linear": "0x43C24",
      "nearOffset": "0x9894"
    },
    "_facecount": {
      "name": "_facecount",
      "segment": "0x3A39",
      "offset": "0xA4E0",
      "linear": "0x44870",
      "nearOffset": "0xA4E0"
    },
    "_gotgatgun": {
      "name": "_gotgatgun",
      "segment": "0x3A39",
      "offset": "0xE00B",
      "linear": "0x4839B",
      "nearOffset": "0xE00B"
    }
  },
  "statetypeSymbols": [
    {
      "name": "_s_player",
      "segment": "0x3A39",
      "offset": "0x190C",
      "linear": "0x3BC9C",
      "nearOffset": "0x190C"
    },
    {
      "name": "_s_attack",
      "segment": "0x3A39",
      "offset": "0x191C",
      "linear": "0x3BCAC",
      "nearOffset": "0x191C"
    },
    {
      "name": "_s_rocket",
      "segment": "0x3A39",
      "offset": "0x1BFA",
      "linear": "0x3BF8A",
      "nearOffset": "0x1BFA"
    },
    {
      "name": "_s_smoke1",
      "segment": "0x3A39",
      "offset": "0x1C0A",
      "linear": "0x3BF9A",
      "nearOffset": "0x1C0A"
    },
    {
      "name": "_s_smoke2",
      "segment": "0x3A39",
      "offset": "0x1C1A",
      "linear": "0x3BFAA",
      "nearOffset": "0x1C1A"
    },
    {
      "name": "_s_smoke3",
      "segment": "0x3A39",
      "offset": "0x1C2A",
      "linear": "0x3BFBA",
      "nearOffset": "0x1C2A"
    },
    {
      "name": "_s_smoke4",
      "segment": "0x3A39",
      "offset": "0x1C3A",
      "linear": "0x3BFCA",
      "nearOffset": "0x1C3A"
    },
    {
      "name": "_s_boom1",
      "segment": "0x3A39",
      "offset": "0x1C4A",
      "linear": "0x3BFDA",
      "nearOffset": "0x1C4A"
    },
    {
      "name": "_s_boom2",
      "segment": "0x3A39",
      "offset": "0x1C5A",
      "linear": "0x3BFEA",
      "nearOffset": "0x1C5A"
    },
    {
      "name": "_s_boom3",
      "segment": "0x3A39",
      "offset": "0x1C6A",
      "linear": "0x3BFFA",
      "nearOffset": "0x1C6A"
    },
    {
      "name": "_s_grdstand",
      "segment": "0x3A39",
      "offset": "0x1C7A",
      "linear": "0x3C00A",
      "nearOffset": "0x1C7A"
    },
    {
      "name": "_s_grdpath1",
      "segment": "0x3A39",
      "offset": "0x1C8A",
      "linear": "0x3C01A",
      "nearOffset": "0x1C8A"
    },
    {
      "name": "_s_grdpath1s",
      "segment": "0x3A39",
      "offset": "0x1C9A",
      "linear": "0x3C02A",
      "nearOffset": "0x1C9A"
    },
    {
      "name": "_s_grdpath2",
      "segment": "0x3A39",
      "offset": "0x1CAA",
      "linear": "0x3C03A",
      "nearOffset": "0x1CAA"
    },
    {
      "name": "_s_grdpath3",
      "segment": "0x3A39",
      "offset": "0x1CBA",
      "linear": "0x3C04A",
      "nearOffset": "0x1CBA"
    },
    {
      "name": "_s_grdpath3s",
      "segment": "0x3A39",
      "offset": "0x1CCA",
      "linear": "0x3C05A",
      "nearOffset": "0x1CCA"
    },
    {
      "name": "_s_grdpath4",
      "segment": "0x3A39",
      "offset": "0x1CDA",
      "linear": "0x3C06A",
      "nearOffset": "0x1CDA"
    },
    {
      "name": "_s_grdpain",
      "segment": "0x3A39",
      "offset": "0x1CEA",
      "linear": "0x3C07A",
      "nearOffset": "0x1CEA"
    },
    {
      "name": "_s_grdpain1",
      "segment": "0x3A39",
      "offset": "0x1CFA",
      "linear": "0x3C08A",
      "nearOffset": "0x1CFA"
    },
    {
      "name": "_s_grdshoot1",
      "segment": "0x3A39",
      "offset": "0x1D0A",
      "linear": "0x3C09A",
      "nearOffset": "0x1D0A"
    },
    {
      "name": "_s_grdshoot2",
      "segment": "0x3A39",
      "offset": "0x1D1A",
      "linear": "0x3C0AA",
      "nearOffset": "0x1D1A"
    },
    {
      "name": "_s_grdshoot3",
      "segment": "0x3A39",
      "offset": "0x1D2A",
      "linear": "0x3C0BA",
      "nearOffset": "0x1D2A"
    },
    {
      "name": "_s_grdchase1",
      "segment": "0x3A39",
      "offset": "0x1D3A",
      "linear": "0x3C0CA",
      "nearOffset": "0x1D3A"
    },
    {
      "name": "_s_grdchase1s",
      "segment": "0x3A39",
      "offset": "0x1D4A",
      "linear": "0x3C0DA",
      "nearOffset": "0x1D4A"
    },
    {
      "name": "_s_grdchase2",
      "segment": "0x3A39",
      "offset": "0x1D5A",
      "linear": "0x3C0EA",
      "nearOffset": "0x1D5A"
    },
    {
      "name": "_s_grdchase3",
      "segment": "0x3A39",
      "offset": "0x1D6A",
      "linear": "0x3C0FA",
      "nearOffset": "0x1D6A"
    },
    {
      "name": "_s_grdchase3s",
      "segment": "0x3A39",
      "offset": "0x1D7A",
      "linear": "0x3C10A",
      "nearOffset": "0x1D7A"
    },
    {
      "name": "_s_grdchase4",
      "segment": "0x3A39",
      "offset": "0x1D8A",
      "linear": "0x3C11A",
      "nearOffset": "0x1D8A"
    },
    {
      "name": "_s_grddie1",
      "segment": "0x3A39",
      "offset": "0x1D9A",
      "linear": "0x3C12A",
      "nearOffset": "0x1D9A"
    },
    {
      "name": "_s_grddie2",
      "segment": "0x3A39",
      "offset": "0x1DAA",
      "linear": "0x3C13A",
      "nearOffset": "0x1DAA"
    },
    {
      "name": "_s_grddie3",
      "segment": "0x3A39",
      "offset": "0x1DBA",
      "linear": "0x3C14A",
      "nearOffset": "0x1DBA"
    },
    {
      "name": "_s_grddie4",
      "segment": "0x3A39",
      "offset": "0x1DCA",
      "linear": "0x3C15A",
      "nearOffset": "0x1DCA"
    },
    {
      "name": "_s_blinkychase1",
      "segment": "0x3A39",
      "offset": "0x1DDA",
      "linear": "0x3C16A",
      "nearOffset": "0x1DDA"
    },
    {
      "name": "_s_blinkychase2",
      "segment": "0x3A39",
      "offset": "0x1DEA",
      "linear": "0x3C17A",
      "nearOffset": "0x1DEA"
    },
    {
      "name": "_s_inkychase1",
      "segment": "0x3A39",
      "offset": "0x1DFA",
      "linear": "0x3C18A",
      "nearOffset": "0x1DFA"
    },
    {
      "name": "_s_inkychase2",
      "segment": "0x3A39",
      "offset": "0x1E0A",
      "linear": "0x3C19A",
      "nearOffset": "0x1E0A"
    },
    {
      "name": "_s_pinkychase1",
      "segment": "0x3A39",
      "offset": "0x1E1A",
      "linear": "0x3C1AA",
      "nearOffset": "0x1E1A"
    },
    {
      "name": "_s_pinkychase2",
      "segment": "0x3A39",
      "offset": "0x1E2A",
      "linear": "0x3C1BA",
      "nearOffset": "0x1E2A"
    },
    {
      "name": "_s_clydechase1",
      "segment": "0x3A39",
      "offset": "0x1E3A",
      "linear": "0x3C1CA",
      "nearOffset": "0x1E3A"
    },
    {
      "name": "_s_clydechase2",
      "segment": "0x3A39",
      "offset": "0x1E4A",
      "linear": "0x3C1DA",
      "nearOffset": "0x1E4A"
    },
    {
      "name": "_s_dogpath1",
      "segment": "0x3A39",
      "offset": "0x1E5A",
      "linear": "0x3C1EA",
      "nearOffset": "0x1E5A"
    },
    {
      "name": "_s_dogpath1s",
      "segment": "0x3A39",
      "offset": "0x1E6A",
      "linear": "0x3C1FA",
      "nearOffset": "0x1E6A"
    },
    {
      "name": "_s_dogpath2",
      "segment": "0x3A39",
      "offset": "0x1E7A",
      "linear": "0x3C20A",
      "nearOffset": "0x1E7A"
    },
    {
      "name": "_s_dogpath3",
      "segment": "0x3A39",
      "offset": "0x1E8A",
      "linear": "0x3C21A",
      "nearOffset": "0x1E8A"
    },
    {
      "name": "_s_dogpath3s",
      "segment": "0x3A39",
      "offset": "0x1E9A",
      "linear": "0x3C22A",
      "nearOffset": "0x1E9A"
    },
    {
      "name": "_s_dogpath4",
      "segment": "0x3A39",
      "offset": "0x1EAA",
      "linear": "0x3C23A",
      "nearOffset": "0x1EAA"
    },
    {
      "name": "_s_dogjump1",
      "segment": "0x3A39",
      "offset": "0x1EBA",
      "linear": "0x3C24A",
      "nearOffset": "0x1EBA"
    },
    {
      "name": "_s_dogjump2",
      "segment": "0x3A39",
      "offset": "0x1ECA",
      "linear": "0x3C25A",
      "nearOffset": "0x1ECA"
    },
    {
      "name": "_s_dogjump3",
      "segment": "0x3A39",
      "offset": "0x1EDA",
      "linear": "0x3C26A",
      "nearOffset": "0x1EDA"
    },
    {
      "name": "_s_dogjump4",
      "segment": "0x3A39",
      "offset": "0x1EEA",
      "linear": "0x3C27A",
      "nearOffset": "0x1EEA"
    },
    {
      "name": "_s_dogjump5",
      "segment": "0x3A39",
      "offset": "0x1EFA",
      "linear": "0x3C28A",
      "nearOffset": "0x1EFA"
    },
    {
      "name": "_s_dogchase1",
      "segment": "0x3A39",
      "offset": "0x1F0A",
      "linear": "0x3C29A",
      "nearOffset": "0x1F0A"
    },
    {
      "name": "_s_dogchase1s",
      "segment": "0x3A39",
      "offset": "0x1F1A",
      "linear": "0x3C2AA",
      "nearOffset": "0x1F1A"
    },
    {
      "name": "_s_dogchase2",
      "segment": "0x3A39",
      "offset": "0x1F2A",
      "linear": "0x3C2BA",
      "nearOffset": "0x1F2A"
    },
    {
      "name": "_s_dogchase3",
      "segment": "0x3A39",
      "offset": "0x1F3A",
      "linear": "0x3C2CA",
      "nearOffset": "0x1F3A"
    },
    {
      "name": "_s_dogchase3s",
      "segment": "0x3A39",
      "offset": "0x1F4A",
      "linear": "0x3C2DA",
      "nearOffset": "0x1F4A"
    },
    {
      "name": "_s_dogchase4",
      "segment": "0x3A39",
      "offset": "0x1F5A",
      "linear": "0x3C2EA",
      "nearOffset": "0x1F5A"
    },
    {
      "name": "_s_dogdie1",
      "segment": "0x3A39",
      "offset": "0x1F6A",
      "linear": "0x3C2FA",
      "nearOffset": "0x1F6A"
    },
    {
      "name": "_s_dogdie2",
      "segment": "0x3A39",
      "offset": "0x1F7A",
      "linear": "0x3C30A",
      "nearOffset": "0x1F7A"
    },
    {
      "name": "_s_dogdie3",
      "segment": "0x3A39",
      "offset": "0x1F8A",
      "linear": "0x3C31A",
      "nearOffset": "0x1F8A"
    },
    {
      "name": "_s_dogdead",
      "segment": "0x3A39",
      "offset": "0x1F9A",
      "linear": "0x3C32A",
      "nearOffset": "0x1F9A"
    },
    {
      "name": "_s_ofcstand",
      "segment": "0x3A39",
      "offset": "0x1FAA",
      "linear": "0x3C33A",
      "nearOffset": "0x1FAA"
    },
    {
      "name": "_s_ofcpath1",
      "segment": "0x3A39",
      "offset": "0x1FBA",
      "linear": "0x3C34A",
      "nearOffset": "0x1FBA"
    },
    {
      "name": "_s_ofcpath1s",
      "segment": "0x3A39",
      "offset": "0x1FCA",
      "linear": "0x3C35A",
      "nearOffset": "0x1FCA"
    },
    {
      "name": "_s_ofcpath2",
      "segment": "0x3A39",
      "offset": "0x1FDA",
      "linear": "0x3C36A",
      "nearOffset": "0x1FDA"
    },
    {
      "name": "_s_ofcpath3",
      "segment": "0x3A39",
      "offset": "0x1FEA",
      "linear": "0x3C37A",
      "nearOffset": "0x1FEA"
    },
    {
      "name": "_s_ofcpath3s",
      "segment": "0x3A39",
      "offset": "0x1FFA",
      "linear": "0x3C38A",
      "nearOffset": "0x1FFA"
    },
    {
      "name": "_s_ofcpath4",
      "segment": "0x3A39",
      "offset": "0x200A",
      "linear": "0x3C39A",
      "nearOffset": "0x200A"
    },
    {
      "name": "_s_ofcpain",
      "segment": "0x3A39",
      "offset": "0x201A",
      "linear": "0x3C3AA",
      "nearOffset": "0x201A"
    },
    {
      "name": "_s_ofcpain1",
      "segment": "0x3A39",
      "offset": "0x202A",
      "linear": "0x3C3BA",
      "nearOffset": "0x202A"
    },
    {
      "name": "_s_ofcshoot1",
      "segment": "0x3A39",
      "offset": "0x203A",
      "linear": "0x3C3CA",
      "nearOffset": "0x203A"
    },
    {
      "name": "_s_ofcshoot2",
      "segment": "0x3A39",
      "offset": "0x204A",
      "linear": "0x3C3DA",
      "nearOffset": "0x204A"
    },
    {
      "name": "_s_ofcshoot3",
      "segment": "0x3A39",
      "offset": "0x205A",
      "linear": "0x3C3EA",
      "nearOffset": "0x205A"
    },
    {
      "name": "_s_ofcchase1",
      "segment": "0x3A39",
      "offset": "0x206A",
      "linear": "0x3C3FA",
      "nearOffset": "0x206A"
    },
    {
      "name": "_s_ofcchase1s",
      "segment": "0x3A39",
      "offset": "0x207A",
      "linear": "0x3C40A",
      "nearOffset": "0x207A"
    },
    {
      "name": "_s_ofcchase2",
      "segment": "0x3A39",
      "offset": "0x208A",
      "linear": "0x3C41A",
      "nearOffset": "0x208A"
    },
    {
      "name": "_s_ofcchase3",
      "segment": "0x3A39",
      "offset": "0x209A",
      "linear": "0x3C42A",
      "nearOffset": "0x209A"
    },
    {
      "name": "_s_ofcchase3s",
      "segment": "0x3A39",
      "offset": "0x20AA",
      "linear": "0x3C43A",
      "nearOffset": "0x20AA"
    },
    {
      "name": "_s_ofcchase4",
      "segment": "0x3A39",
      "offset": "0x20BA",
      "linear": "0x3C44A",
      "nearOffset": "0x20BA"
    },
    {
      "name": "_s_ofcdie1",
      "segment": "0x3A39",
      "offset": "0x20CA",
      "linear": "0x3C45A",
      "nearOffset": "0x20CA"
    },
    {
      "name": "_s_ofcdie2",
      "segment": "0x3A39",
      "offset": "0x20DA",
      "linear": "0x3C46A",
      "nearOffset": "0x20DA"
    },
    {
      "name": "_s_ofcdie3",
      "segment": "0x3A39",
      "offset": "0x20EA",
      "linear": "0x3C47A",
      "nearOffset": "0x20EA"
    },
    {
      "name": "_s_ofcdie4",
      "segment": "0x3A39",
      "offset": "0x20FA",
      "linear": "0x3C48A",
      "nearOffset": "0x20FA"
    },
    {
      "name": "_s_ofcdie5",
      "segment": "0x3A39",
      "offset": "0x210A",
      "linear": "0x3C49A",
      "nearOffset": "0x210A"
    },
    {
      "name": "_s_mutstand",
      "segment": "0x3A39",
      "offset": "0x211A",
      "linear": "0x3C4AA",
      "nearOffset": "0x211A"
    },
    {
      "name": "_s_mutpath1",
      "segment": "0x3A39",
      "offset": "0x212A",
      "linear": "0x3C4BA",
      "nearOffset": "0x212A"
    },
    {
      "name": "_s_mutpath1s",
      "segment": "0x3A39",
      "offset": "0x213A",
      "linear": "0x3C4CA",
      "nearOffset": "0x213A"
    },
    {
      "name": "_s_mutpath2",
      "segment": "0x3A39",
      "offset": "0x214A",
      "linear": "0x3C4DA",
      "nearOffset": "0x214A"
    },
    {
      "name": "_s_mutpath3",
      "segment": "0x3A39",
      "offset": "0x215A",
      "linear": "0x3C4EA",
      "nearOffset": "0x215A"
    },
    {
      "name": "_s_mutpath3s",
      "segment": "0x3A39",
      "offset": "0x216A",
      "linear": "0x3C4FA",
      "nearOffset": "0x216A"
    },
    {
      "name": "_s_mutpath4",
      "segment": "0x3A39",
      "offset": "0x217A",
      "linear": "0x3C50A",
      "nearOffset": "0x217A"
    },
    {
      "name": "_s_mutpain",
      "segment": "0x3A39",
      "offset": "0x218A",
      "linear": "0x3C51A",
      "nearOffset": "0x218A"
    },
    {
      "name": "_s_mutpain1",
      "segment": "0x3A39",
      "offset": "0x219A",
      "linear": "0x3C52A",
      "nearOffset": "0x219A"
    },
    {
      "name": "_s_mutshoot1",
      "segment": "0x3A39",
      "offset": "0x21AA",
      "linear": "0x3C53A",
      "nearOffset": "0x21AA"
    },
    {
      "name": "_s_mutshoot2",
      "segment": "0x3A39",
      "offset": "0x21BA",
      "linear": "0x3C54A",
      "nearOffset": "0x21BA"
    },
    {
      "name": "_s_mutshoot3",
      "segment": "0x3A39",
      "offset": "0x21CA",
      "linear": "0x3C55A",
      "nearOffset": "0x21CA"
    },
    {
      "name": "_s_mutshoot4",
      "segment": "0x3A39",
      "offset": "0x21DA",
      "linear": "0x3C56A",
      "nearOffset": "0x21DA"
    },
    {
      "name": "_s_mutchase1",
      "segment": "0x3A39",
      "offset": "0x21EA",
      "linear": "0x3C57A",
      "nearOffset": "0x21EA"
    },
    {
      "name": "_s_mutchase1s",
      "segment": "0x3A39",
      "offset": "0x21FA",
      "linear": "0x3C58A",
      "nearOffset": "0x21FA"
    },
    {
      "name": "_s_mutchase2",
      "segment": "0x3A39",
      "offset": "0x220A",
      "linear": "0x3C59A",
      "nearOffset": "0x220A"
    },
    {
      "name": "_s_mutchase3",
      "segment": "0x3A39",
      "offset": "0x221A",
      "linear": "0x3C5AA",
      "nearOffset": "0x221A"
    },
    {
      "name": "_s_mutchase3s",
      "segment": "0x3A39",
      "offset": "0x222A",
      "linear": "0x3C5BA",
      "nearOffset": "0x222A"
    },
    {
      "name": "_s_mutchase4",
      "segment": "0x3A39",
      "offset": "0x223A",
      "linear": "0x3C5CA",
      "nearOffset": "0x223A"
    },
    {
      "name": "_s_mutdie1",
      "segment": "0x3A39",
      "offset": "0x224A",
      "linear": "0x3C5DA",
      "nearOffset": "0x224A"
    },
    {
      "name": "_s_mutdie2",
      "segment": "0x3A39",
      "offset": "0x225A",
      "linear": "0x3C5EA",
      "nearOffset": "0x225A"
    },
    {
      "name": "_s_mutdie3",
      "segment": "0x3A39",
      "offset": "0x226A",
      "linear": "0x3C5FA",
      "nearOffset": "0x226A"
    },
    {
      "name": "_s_mutdie4",
      "segment": "0x3A39",
      "offset": "0x227A",
      "linear": "0x3C60A",
      "nearOffset": "0x227A"
    },
    {
      "name": "_s_mutdie5",
      "segment": "0x3A39",
      "offset": "0x228A",
      "linear": "0x3C61A",
      "nearOffset": "0x228A"
    },
    {
      "name": "_s_ssstand",
      "segment": "0x3A39",
      "offset": "0x229A",
      "linear": "0x3C62A",
      "nearOffset": "0x229A"
    },
    {
      "name": "_s_sspath1",
      "segment": "0x3A39",
      "offset": "0x22AA",
      "linear": "0x3C63A",
      "nearOffset": "0x22AA"
    },
    {
      "name": "_s_sspath1s",
      "segment": "0x3A39",
      "offset": "0x22BA",
      "linear": "0x3C64A",
      "nearOffset": "0x22BA"
    },
    {
      "name": "_s_sspath2",
      "segment": "0x3A39",
      "offset": "0x22CA",
      "linear": "0x3C65A",
      "nearOffset": "0x22CA"
    },
    {
      "name": "_s_sspath3",
      "segment": "0x3A39",
      "offset": "0x22DA",
      "linear": "0x3C66A",
      "nearOffset": "0x22DA"
    },
    {
      "name": "_s_sspath3s",
      "segment": "0x3A39",
      "offset": "0x22EA",
      "linear": "0x3C67A",
      "nearOffset": "0x22EA"
    },
    {
      "name": "_s_sspath4",
      "segment": "0x3A39",
      "offset": "0x22FA",
      "linear": "0x3C68A",
      "nearOffset": "0x22FA"
    },
    {
      "name": "_s_sspain",
      "segment": "0x3A39",
      "offset": "0x230A",
      "linear": "0x3C69A",
      "nearOffset": "0x230A"
    },
    {
      "name": "_s_sspain1",
      "segment": "0x3A39",
      "offset": "0x231A",
      "linear": "0x3C6AA",
      "nearOffset": "0x231A"
    },
    {
      "name": "_s_ssshoot1",
      "segment": "0x3A39",
      "offset": "0x232A",
      "linear": "0x3C6BA",
      "nearOffset": "0x232A"
    },
    {
      "name": "_s_ssshoot2",
      "segment": "0x3A39",
      "offset": "0x233A",
      "linear": "0x3C6CA",
      "nearOffset": "0x233A"
    },
    {
      "name": "_s_ssshoot3",
      "segment": "0x3A39",
      "offset": "0x234A",
      "linear": "0x3C6DA",
      "nearOffset": "0x234A"
    },
    {
      "name": "_s_ssshoot4",
      "segment": "0x3A39",
      "offset": "0x235A",
      "linear": "0x3C6EA",
      "nearOffset": "0x235A"
    },
    {
      "name": "_s_ssshoot5",
      "segment": "0x3A39",
      "offset": "0x236A",
      "linear": "0x3C6FA",
      "nearOffset": "0x236A"
    },
    {
      "name": "_s_ssshoot6",
      "segment": "0x3A39",
      "offset": "0x237A",
      "linear": "0x3C70A",
      "nearOffset": "0x237A"
    },
    {
      "name": "_s_ssshoot7",
      "segment": "0x3A39",
      "offset": "0x238A",
      "linear": "0x3C71A",
      "nearOffset": "0x238A"
    },
    {
      "name": "_s_ssshoot8",
      "segment": "0x3A39",
      "offset": "0x239A",
      "linear": "0x3C72A",
      "nearOffset": "0x239A"
    },
    {
      "name": "_s_ssshoot9",
      "segment": "0x3A39",
      "offset": "0x23AA",
      "linear": "0x3C73A",
      "nearOffset": "0x23AA"
    },
    {
      "name": "_s_sschase1",
      "segment": "0x3A39",
      "offset": "0x23BA",
      "linear": "0x3C74A",
      "nearOffset": "0x23BA"
    },
    {
      "name": "_s_sschase1s",
      "segment": "0x3A39",
      "offset": "0x23CA",
      "linear": "0x3C75A",
      "nearOffset": "0x23CA"
    },
    {
      "name": "_s_sschase2",
      "segment": "0x3A39",
      "offset": "0x23DA",
      "linear": "0x3C76A",
      "nearOffset": "0x23DA"
    },
    {
      "name": "_s_sschase3",
      "segment": "0x3A39",
      "offset": "0x23EA",
      "linear": "0x3C77A",
      "nearOffset": "0x23EA"
    },
    {
      "name": "_s_sschase3s",
      "segment": "0x3A39",
      "offset": "0x23FA",
      "linear": "0x3C78A",
      "nearOffset": "0x23FA"
    },
    {
      "name": "_s_sschase4",
      "segment": "0x3A39",
      "offset": "0x240A",
      "linear": "0x3C79A",
      "nearOffset": "0x240A"
    },
    {
      "name": "_s_ssdie1",
      "segment": "0x3A39",
      "offset": "0x241A",
      "linear": "0x3C7AA",
      "nearOffset": "0x241A"
    },
    {
      "name": "_s_ssdie2",
      "segment": "0x3A39",
      "offset": "0x242A",
      "linear": "0x3C7BA",
      "nearOffset": "0x242A"
    },
    {
      "name": "_s_ssdie3",
      "segment": "0x3A39",
      "offset": "0x243A",
      "linear": "0x3C7CA",
      "nearOffset": "0x243A"
    },
    {
      "name": "_s_ssdie4",
      "segment": "0x3A39",
      "offset": "0x244A",
      "linear": "0x3C7DA",
      "nearOffset": "0x244A"
    },
    {
      "name": "_s_bossstand",
      "segment": "0x3A39",
      "offset": "0x245A",
      "linear": "0x3C7EA",
      "nearOffset": "0x245A"
    },
    {
      "name": "_s_bosschase1",
      "segment": "0x3A39",
      "offset": "0x246A",
      "linear": "0x3C7FA",
      "nearOffset": "0x246A"
    },
    {
      "name": "_s_bosschase1s",
      "segment": "0x3A39",
      "offset": "0x247A",
      "linear": "0x3C80A",
      "nearOffset": "0x247A"
    },
    {
      "name": "_s_bosschase2",
      "segment": "0x3A39",
      "offset": "0x248A",
      "linear": "0x3C81A",
      "nearOffset": "0x248A"
    },
    {
      "name": "_s_bosschase3",
      "segment": "0x3A39",
      "offset": "0x249A",
      "linear": "0x3C82A",
      "nearOffset": "0x249A"
    },
    {
      "name": "_s_bosschase3s",
      "segment": "0x3A39",
      "offset": "0x24AA",
      "linear": "0x3C83A",
      "nearOffset": "0x24AA"
    },
    {
      "name": "_s_bosschase4",
      "segment": "0x3A39",
      "offset": "0x24BA",
      "linear": "0x3C84A",
      "nearOffset": "0x24BA"
    },
    {
      "name": "_s_bossdie1",
      "segment": "0x3A39",
      "offset": "0x24CA",
      "linear": "0x3C85A",
      "nearOffset": "0x24CA"
    },
    {
      "name": "_s_bossdie2",
      "segment": "0x3A39",
      "offset": "0x24DA",
      "linear": "0x3C86A",
      "nearOffset": "0x24DA"
    },
    {
      "name": "_s_bossdie3",
      "segment": "0x3A39",
      "offset": "0x24EA",
      "linear": "0x3C87A",
      "nearOffset": "0x24EA"
    },
    {
      "name": "_s_bossdie4",
      "segment": "0x3A39",
      "offset": "0x24FA",
      "linear": "0x3C88A",
      "nearOffset": "0x24FA"
    },
    {
      "name": "_s_bossshoot1",
      "segment": "0x3A39",
      "offset": "0x250A",
      "linear": "0x3C89A",
      "nearOffset": "0x250A"
    },
    {
      "name": "_s_bossshoot2",
      "segment": "0x3A39",
      "offset": "0x251A",
      "linear": "0x3C8AA",
      "nearOffset": "0x251A"
    },
    {
      "name": "_s_bossshoot3",
      "segment": "0x3A39",
      "offset": "0x252A",
      "linear": "0x3C8BA",
      "nearOffset": "0x252A"
    },
    {
      "name": "_s_bossshoot4",
      "segment": "0x3A39",
      "offset": "0x253A",
      "linear": "0x3C8CA",
      "nearOffset": "0x253A"
    },
    {
      "name": "_s_bossshoot5",
      "segment": "0x3A39",
      "offset": "0x254A",
      "linear": "0x3C8DA",
      "nearOffset": "0x254A"
    },
    {
      "name": "_s_bossshoot6",
      "segment": "0x3A39",
      "offset": "0x255A",
      "linear": "0x3C8EA",
      "nearOffset": "0x255A"
    },
    {
      "name": "_s_bossshoot7",
      "segment": "0x3A39",
      "offset": "0x256A",
      "linear": "0x3C8FA",
      "nearOffset": "0x256A"
    },
    {
      "name": "_s_bossshoot8",
      "segment": "0x3A39",
      "offset": "0x257A",
      "linear": "0x3C90A",
      "nearOffset": "0x257A"
    },
    {
      "name": "_s_gretelstand",
      "segment": "0x3A39",
      "offset": "0x258A",
      "linear": "0x3C91A",
      "nearOffset": "0x258A"
    },
    {
      "name": "_s_gretelchase1",
      "segment": "0x3A39",
      "offset": "0x259A",
      "linear": "0x3C92A",
      "nearOffset": "0x259A"
    },
    {
      "name": "_s_gretelchase1s",
      "segment": "0x3A39",
      "offset": "0x25AA",
      "linear": "0x3C93A",
      "nearOffset": "0x25AA"
    },
    {
      "name": "_s_gretelchase2",
      "segment": "0x3A39",
      "offset": "0x25BA",
      "linear": "0x3C94A",
      "nearOffset": "0x25BA"
    },
    {
      "name": "_s_gretelchase3",
      "segment": "0x3A39",
      "offset": "0x25CA",
      "linear": "0x3C95A",
      "nearOffset": "0x25CA"
    },
    {
      "name": "_s_gretelchase3s",
      "segment": "0x3A39",
      "offset": "0x25DA",
      "linear": "0x3C96A",
      "nearOffset": "0x25DA"
    },
    {
      "name": "_s_gretelchase4",
      "segment": "0x3A39",
      "offset": "0x25EA",
      "linear": "0x3C97A",
      "nearOffset": "0x25EA"
    },
    {
      "name": "_s_greteldie1",
      "segment": "0x3A39",
      "offset": "0x25FA",
      "linear": "0x3C98A",
      "nearOffset": "0x25FA"
    },
    {
      "name": "_s_greteldie2",
      "segment": "0x3A39",
      "offset": "0x260A",
      "linear": "0x3C99A",
      "nearOffset": "0x260A"
    },
    {
      "name": "_s_greteldie3",
      "segment": "0x3A39",
      "offset": "0x261A",
      "linear": "0x3C9AA",
      "nearOffset": "0x261A"
    },
    {
      "name": "_s_greteldie4",
      "segment": "0x3A39",
      "offset": "0x262A",
      "linear": "0x3C9BA",
      "nearOffset": "0x262A"
    },
    {
      "name": "_s_gretelshoot1",
      "segment": "0x3A39",
      "offset": "0x263A",
      "linear": "0x3C9CA",
      "nearOffset": "0x263A"
    },
    {
      "name": "_s_gretelshoot2",
      "segment": "0x3A39",
      "offset": "0x264A",
      "linear": "0x3C9DA",
      "nearOffset": "0x264A"
    },
    {
      "name": "_s_gretelshoot3",
      "segment": "0x3A39",
      "offset": "0x265A",
      "linear": "0x3C9EA",
      "nearOffset": "0x265A"
    },
    {
      "name": "_s_gretelshoot4",
      "segment": "0x3A39",
      "offset": "0x266A",
      "linear": "0x3C9FA",
      "nearOffset": "0x266A"
    },
    {
      "name": "_s_gretelshoot5",
      "segment": "0x3A39",
      "offset": "0x267A",
      "linear": "0x3CA0A",
      "nearOffset": "0x267A"
    },
    {
      "name": "_s_gretelshoot6",
      "segment": "0x3A39",
      "offset": "0x268A",
      "linear": "0x3CA1A",
      "nearOffset": "0x268A"
    },
    {
      "name": "_s_gretelshoot7",
      "segment": "0x3A39",
      "offset": "0x269A",
      "linear": "0x3CA2A",
      "nearOffset": "0x269A"
    },
    {
      "name": "_s_gretelshoot8",
      "segment": "0x3A39",
      "offset": "0x26AA",
      "linear": "0x3CA3A",
      "nearOffset": "0x26AA"
    },
    {
      "name": "_s_schabbstand",
      "segment": "0x3A39",
      "offset": "0x26CC",
      "linear": "0x3CA5C",
      "nearOffset": "0x26CC"
    },
    {
      "name": "_s_schabbchase1",
      "segment": "0x3A39",
      "offset": "0x26DC",
      "linear": "0x3CA6C",
      "nearOffset": "0x26DC"
    },
    {
      "name": "_s_schabbchase1s",
      "segment": "0x3A39",
      "offset": "0x26EC",
      "linear": "0x3CA7C",
      "nearOffset": "0x26EC"
    },
    {
      "name": "_s_schabbchase2",
      "segment": "0x3A39",
      "offset": "0x26FC",
      "linear": "0x3CA8C",
      "nearOffset": "0x26FC"
    },
    {
      "name": "_s_schabbchase3",
      "segment": "0x3A39",
      "offset": "0x270C",
      "linear": "0x3CA9C",
      "nearOffset": "0x270C"
    },
    {
      "name": "_s_schabbchase3s",
      "segment": "0x3A39",
      "offset": "0x271C",
      "linear": "0x3CAAC",
      "nearOffset": "0x271C"
    },
    {
      "name": "_s_schabbchase4",
      "segment": "0x3A39",
      "offset": "0x272C",
      "linear": "0x3CABC",
      "nearOffset": "0x272C"
    },
    {
      "name": "_s_schabbdeathcam",
      "segment": "0x3A39",
      "offset": "0x273C",
      "linear": "0x3CACC",
      "nearOffset": "0x273C"
    },
    {
      "name": "_s_schabbdie1",
      "segment": "0x3A39",
      "offset": "0x274C",
      "linear": "0x3CADC",
      "nearOffset": "0x274C"
    },
    {
      "name": "_s_schabbdie2",
      "segment": "0x3A39",
      "offset": "0x275C",
      "linear": "0x3CAEC",
      "nearOffset": "0x275C"
    },
    {
      "name": "_s_schabbdie3",
      "segment": "0x3A39",
      "offset": "0x276C",
      "linear": "0x3CAFC",
      "nearOffset": "0x276C"
    },
    {
      "name": "_s_schabbdie4",
      "segment": "0x3A39",
      "offset": "0x277C",
      "linear": "0x3CB0C",
      "nearOffset": "0x277C"
    },
    {
      "name": "_s_schabbdie5",
      "segment": "0x3A39",
      "offset": "0x278C",
      "linear": "0x3CB1C",
      "nearOffset": "0x278C"
    },
    {
      "name": "_s_schabbdie6",
      "segment": "0x3A39",
      "offset": "0x279C",
      "linear": "0x3CB2C",
      "nearOffset": "0x279C"
    },
    {
      "name": "_s_schabbshoot1",
      "segment": "0x3A39",
      "offset": "0x27AC",
      "linear": "0x3CB3C",
      "nearOffset": "0x27AC"
    },
    {
      "name": "_s_schabbshoot2",
      "segment": "0x3A39",
      "offset": "0x27BC",
      "linear": "0x3CB4C",
      "nearOffset": "0x27BC"
    },
    {
      "name": "_s_needle1",
      "segment": "0x3A39",
      "offset": "0x27CC",
      "linear": "0x3CB5C",
      "nearOffset": "0x27CC"
    },
    {
      "name": "_s_needle2",
      "segment": "0x3A39",
      "offset": "0x27DC",
      "linear": "0x3CB6C",
      "nearOffset": "0x27DC"
    },
    {
      "name": "_s_needle3",
      "segment": "0x3A39",
      "offset": "0x27EC",
      "linear": "0x3CB7C",
      "nearOffset": "0x27EC"
    },
    {
      "name": "_s_needle4",
      "segment": "0x3A39",
      "offset": "0x27FC",
      "linear": "0x3CB8C",
      "nearOffset": "0x27FC"
    },
    {
      "name": "_s_giftstand",
      "segment": "0x3A39",
      "offset": "0x280C",
      "linear": "0x3CB9C",
      "nearOffset": "0x280C"
    },
    {
      "name": "_s_giftchase1",
      "segment": "0x3A39",
      "offset": "0x281C",
      "linear": "0x3CBAC",
      "nearOffset": "0x281C"
    },
    {
      "name": "_s_giftchase1s",
      "segment": "0x3A39",
      "offset": "0x282C",
      "linear": "0x3CBBC",
      "nearOffset": "0x282C"
    },
    {
      "name": "_s_giftchase2",
      "segment": "0x3A39",
      "offset": "0x283C",
      "linear": "0x3CBCC",
      "nearOffset": "0x283C"
    },
    {
      "name": "_s_giftchase3",
      "segment": "0x3A39",
      "offset": "0x284C",
      "linear": "0x3CBDC",
      "nearOffset": "0x284C"
    },
    {
      "name": "_s_giftchase3s",
      "segment": "0x3A39",
      "offset": "0x285C",
      "linear": "0x3CBEC",
      "nearOffset": "0x285C"
    },
    {
      "name": "_s_giftchase4",
      "segment": "0x3A39",
      "offset": "0x286C",
      "linear": "0x3CBFC",
      "nearOffset": "0x286C"
    },
    {
      "name": "_s_giftdeathcam",
      "segment": "0x3A39",
      "offset": "0x287C",
      "linear": "0x3CC0C",
      "nearOffset": "0x287C"
    },
    {
      "name": "_s_giftdie1",
      "segment": "0x3A39",
      "offset": "0x288C",
      "linear": "0x3CC1C",
      "nearOffset": "0x288C"
    },
    {
      "name": "_s_giftdie2",
      "segment": "0x3A39",
      "offset": "0x289C",
      "linear": "0x3CC2C",
      "nearOffset": "0x289C"
    },
    {
      "name": "_s_giftdie3",
      "segment": "0x3A39",
      "offset": "0x28AC",
      "linear": "0x3CC3C",
      "nearOffset": "0x28AC"
    },
    {
      "name": "_s_giftdie4",
      "segment": "0x3A39",
      "offset": "0x28BC",
      "linear": "0x3CC4C",
      "nearOffset": "0x28BC"
    },
    {
      "name": "_s_giftdie5",
      "segment": "0x3A39",
      "offset": "0x28CC",
      "linear": "0x3CC5C",
      "nearOffset": "0x28CC"
    },
    {
      "name": "_s_giftdie6",
      "segment": "0x3A39",
      "offset": "0x28DC",
      "linear": "0x3CC6C",
      "nearOffset": "0x28DC"
    },
    {
      "name": "_s_giftshoot1",
      "segment": "0x3A39",
      "offset": "0x28EC",
      "linear": "0x3CC7C",
      "nearOffset": "0x28EC"
    },
    {
      "name": "_s_giftshoot2",
      "segment": "0x3A39",
      "offset": "0x28FC",
      "linear": "0x3CC8C",
      "nearOffset": "0x28FC"
    },
    {
      "name": "_s_fatstand",
      "segment": "0x3A39",
      "offset": "0x290C",
      "linear": "0x3CC9C",
      "nearOffset": "0x290C"
    },
    {
      "name": "_s_fatchase1",
      "segment": "0x3A39",
      "offset": "0x291C",
      "linear": "0x3CCAC",
      "nearOffset": "0x291C"
    },
    {
      "name": "_s_fatchase1s",
      "segment": "0x3A39",
      "offset": "0x292C",
      "linear": "0x3CCBC",
      "nearOffset": "0x292C"
    },
    {
      "name": "_s_fatchase2",
      "segment": "0x3A39",
      "offset": "0x293C",
      "linear": "0x3CCCC",
      "nearOffset": "0x293C"
    },
    {
      "name": "_s_fatchase3",
      "segment": "0x3A39",
      "offset": "0x294C",
      "linear": "0x3CCDC",
      "nearOffset": "0x294C"
    },
    {
      "name": "_s_fatchase3s",
      "segment": "0x3A39",
      "offset": "0x295C",
      "linear": "0x3CCEC",
      "nearOffset": "0x295C"
    },
    {
      "name": "_s_fatchase4",
      "segment": "0x3A39",
      "offset": "0x296C",
      "linear": "0x3CCFC",
      "nearOffset": "0x296C"
    },
    {
      "name": "_s_fatdeathcam",
      "segment": "0x3A39",
      "offset": "0x297C",
      "linear": "0x3CD0C",
      "nearOffset": "0x297C"
    },
    {
      "name": "_s_fatdie1",
      "segment": "0x3A39",
      "offset": "0x298C",
      "linear": "0x3CD1C",
      "nearOffset": "0x298C"
    },
    {
      "name": "_s_fatdie2",
      "segment": "0x3A39",
      "offset": "0x299C",
      "linear": "0x3CD2C",
      "nearOffset": "0x299C"
    },
    {
      "name": "_s_fatdie3",
      "segment": "0x3A39",
      "offset": "0x29AC",
      "linear": "0x3CD3C",
      "nearOffset": "0x29AC"
    },
    {
      "name": "_s_fatdie4",
      "segment": "0x3A39",
      "offset": "0x29BC",
      "linear": "0x3CD4C",
      "nearOffset": "0x29BC"
    },
    {
      "name": "_s_fatdie5",
      "segment": "0x3A39",
      "offset": "0x29CC",
      "linear": "0x3CD5C",
      "nearOffset": "0x29CC"
    },
    {
      "name": "_s_fatdie6",
      "segment": "0x3A39",
      "offset": "0x29DC",
      "linear": "0x3CD6C",
      "nearOffset": "0x29DC"
    },
    {
      "name": "_s_fatshoot1",
      "segment": "0x3A39",
      "offset": "0x29EC",
      "linear": "0x3CD7C",
      "nearOffset": "0x29EC"
    },
    {
      "name": "_s_fatshoot2",
      "segment": "0x3A39",
      "offset": "0x29FC",
      "linear": "0x3CD8C",
      "nearOffset": "0x29FC"
    },
    {
      "name": "_s_fatshoot3",
      "segment": "0x3A39",
      "offset": "0x2A0C",
      "linear": "0x3CD9C",
      "nearOffset": "0x2A0C"
    },
    {
      "name": "_s_fatshoot4",
      "segment": "0x3A39",
      "offset": "0x2A1C",
      "linear": "0x3CDAC",
      "nearOffset": "0x2A1C"
    },
    {
      "name": "_s_fatshoot5",
      "segment": "0x3A39",
      "offset": "0x2A2C",
      "linear": "0x3CDBC",
      "nearOffset": "0x2A2C"
    },
    {
      "name": "_s_fatshoot6",
      "segment": "0x3A39",
      "offset": "0x2A3C",
      "linear": "0x3CDCC",
      "nearOffset": "0x2A3C"
    },
    {
      "name": "_s_fakestand",
      "segment": "0x3A39",
      "offset": "0x2A4C",
      "linear": "0x3CDDC",
      "nearOffset": "0x2A4C"
    },
    {
      "name": "_s_fakechase1",
      "segment": "0x3A39",
      "offset": "0x2A5C",
      "linear": "0x3CDEC",
      "nearOffset": "0x2A5C"
    },
    {
      "name": "_s_fakechase1s",
      "segment": "0x3A39",
      "offset": "0x2A6C",
      "linear": "0x3CDFC",
      "nearOffset": "0x2A6C"
    },
    {
      "name": "_s_fakechase2",
      "segment": "0x3A39",
      "offset": "0x2A7C",
      "linear": "0x3CE0C",
      "nearOffset": "0x2A7C"
    },
    {
      "name": "_s_fakechase3",
      "segment": "0x3A39",
      "offset": "0x2A8C",
      "linear": "0x3CE1C",
      "nearOffset": "0x2A8C"
    },
    {
      "name": "_s_fakechase3s",
      "segment": "0x3A39",
      "offset": "0x2A9C",
      "linear": "0x3CE2C",
      "nearOffset": "0x2A9C"
    },
    {
      "name": "_s_fakechase4",
      "segment": "0x3A39",
      "offset": "0x2AAC",
      "linear": "0x3CE3C",
      "nearOffset": "0x2AAC"
    },
    {
      "name": "_s_fakedie1",
      "segment": "0x3A39",
      "offset": "0x2ABC",
      "linear": "0x3CE4C",
      "nearOffset": "0x2ABC"
    },
    {
      "name": "_s_fakedie2",
      "segment": "0x3A39",
      "offset": "0x2ACC",
      "linear": "0x3CE5C",
      "nearOffset": "0x2ACC"
    },
    {
      "name": "_s_fakedie3",
      "segment": "0x3A39",
      "offset": "0x2ADC",
      "linear": "0x3CE6C",
      "nearOffset": "0x2ADC"
    },
    {
      "name": "_s_fakedie4",
      "segment": "0x3A39",
      "offset": "0x2AEC",
      "linear": "0x3CE7C",
      "nearOffset": "0x2AEC"
    },
    {
      "name": "_s_fakedie5",
      "segment": "0x3A39",
      "offset": "0x2AFC",
      "linear": "0x3CE8C",
      "nearOffset": "0x2AFC"
    },
    {
      "name": "_s_fakedie6",
      "segment": "0x3A39",
      "offset": "0x2B0C",
      "linear": "0x3CE9C",
      "nearOffset": "0x2B0C"
    },
    {
      "name": "_s_fakeshoot1",
      "segment": "0x3A39",
      "offset": "0x2B1C",
      "linear": "0x3CEAC",
      "nearOffset": "0x2B1C"
    },
    {
      "name": "_s_fakeshoot2",
      "segment": "0x3A39",
      "offset": "0x2B2C",
      "linear": "0x3CEBC",
      "nearOffset": "0x2B2C"
    },
    {
      "name": "_s_fakeshoot3",
      "segment": "0x3A39",
      "offset": "0x2B3C",
      "linear": "0x3CECC",
      "nearOffset": "0x2B3C"
    },
    {
      "name": "_s_fakeshoot4",
      "segment": "0x3A39",
      "offset": "0x2B4C",
      "linear": "0x3CEDC",
      "nearOffset": "0x2B4C"
    },
    {
      "name": "_s_fakeshoot5",
      "segment": "0x3A39",
      "offset": "0x2B5C",
      "linear": "0x3CEEC",
      "nearOffset": "0x2B5C"
    },
    {
      "name": "_s_fakeshoot6",
      "segment": "0x3A39",
      "offset": "0x2B6C",
      "linear": "0x3CEFC",
      "nearOffset": "0x2B6C"
    },
    {
      "name": "_s_fakeshoot7",
      "segment": "0x3A39",
      "offset": "0x2B7C",
      "linear": "0x3CF0C",
      "nearOffset": "0x2B7C"
    },
    {
      "name": "_s_fakeshoot8",
      "segment": "0x3A39",
      "offset": "0x2B8C",
      "linear": "0x3CF1C",
      "nearOffset": "0x2B8C"
    },
    {
      "name": "_s_fakeshoot9",
      "segment": "0x3A39",
      "offset": "0x2B9C",
      "linear": "0x3CF2C",
      "nearOffset": "0x2B9C"
    },
    {
      "name": "_s_fire1",
      "segment": "0x3A39",
      "offset": "0x2BAC",
      "linear": "0x3CF3C",
      "nearOffset": "0x2BAC"
    },
    {
      "name": "_s_fire2",
      "segment": "0x3A39",
      "offset": "0x2BBC",
      "linear": "0x3CF4C",
      "nearOffset": "0x2BBC"
    },
    {
      "name": "_s_mechastand",
      "segment": "0x3A39",
      "offset": "0x2BCC",
      "linear": "0x3CF5C",
      "nearOffset": "0x2BCC"
    },
    {
      "name": "_s_mechachase1",
      "segment": "0x3A39",
      "offset": "0x2BDC",
      "linear": "0x3CF6C",
      "nearOffset": "0x2BDC"
    },
    {
      "name": "_s_mechachase1s",
      "segment": "0x3A39",
      "offset": "0x2BEC",
      "linear": "0x3CF7C",
      "nearOffset": "0x2BEC"
    },
    {
      "name": "_s_mechachase2",
      "segment": "0x3A39",
      "offset": "0x2BFC",
      "linear": "0x3CF8C",
      "nearOffset": "0x2BFC"
    },
    {
      "name": "_s_mechachase3",
      "segment": "0x3A39",
      "offset": "0x2C0C",
      "linear": "0x3CF9C",
      "nearOffset": "0x2C0C"
    },
    {
      "name": "_s_mechachase3s",
      "segment": "0x3A39",
      "offset": "0x2C1C",
      "linear": "0x3CFAC",
      "nearOffset": "0x2C1C"
    },
    {
      "name": "_s_mechachase4",
      "segment": "0x3A39",
      "offset": "0x2C2C",
      "linear": "0x3CFBC",
      "nearOffset": "0x2C2C"
    },
    {
      "name": "_s_mechadie1",
      "segment": "0x3A39",
      "offset": "0x2C3C",
      "linear": "0x3CFCC",
      "nearOffset": "0x2C3C"
    },
    {
      "name": "_s_mechadie2",
      "segment": "0x3A39",
      "offset": "0x2C4C",
      "linear": "0x3CFDC",
      "nearOffset": "0x2C4C"
    },
    {
      "name": "_s_mechadie3",
      "segment": "0x3A39",
      "offset": "0x2C5C",
      "linear": "0x3CFEC",
      "nearOffset": "0x2C5C"
    },
    {
      "name": "_s_mechadie4",
      "segment": "0x3A39",
      "offset": "0x2C6C",
      "linear": "0x3CFFC",
      "nearOffset": "0x2C6C"
    },
    {
      "name": "_s_mechashoot1",
      "segment": "0x3A39",
      "offset": "0x2C7C",
      "linear": "0x3D00C",
      "nearOffset": "0x2C7C"
    },
    {
      "name": "_s_mechashoot2",
      "segment": "0x3A39",
      "offset": "0x2C8C",
      "linear": "0x3D01C",
      "nearOffset": "0x2C8C"
    },
    {
      "name": "_s_mechashoot3",
      "segment": "0x3A39",
      "offset": "0x2C9C",
      "linear": "0x3D02C",
      "nearOffset": "0x2C9C"
    },
    {
      "name": "_s_mechashoot4",
      "segment": "0x3A39",
      "offset": "0x2CAC",
      "linear": "0x3D03C",
      "nearOffset": "0x2CAC"
    },
    {
      "name": "_s_mechashoot5",
      "segment": "0x3A39",
      "offset": "0x2CBC",
      "linear": "0x3D04C",
      "nearOffset": "0x2CBC"
    },
    {
      "name": "_s_mechashoot6",
      "segment": "0x3A39",
      "offset": "0x2CCC",
      "linear": "0x3D05C",
      "nearOffset": "0x2CCC"
    },
    {
      "name": "_s_hitlerchase1",
      "segment": "0x3A39",
      "offset": "0x2CDC",
      "linear": "0x3D06C",
      "nearOffset": "0x2CDC"
    },
    {
      "name": "_s_hitlerchase1s",
      "segment": "0x3A39",
      "offset": "0x2CEC",
      "linear": "0x3D07C",
      "nearOffset": "0x2CEC"
    },
    {
      "name": "_s_hitlerchase2",
      "segment": "0x3A39",
      "offset": "0x2CFC",
      "linear": "0x3D08C",
      "nearOffset": "0x2CFC"
    },
    {
      "name": "_s_hitlerchase3",
      "segment": "0x3A39",
      "offset": "0x2D0C",
      "linear": "0x3D09C",
      "nearOffset": "0x2D0C"
    },
    {
      "name": "_s_hitlerchase3s",
      "segment": "0x3A39",
      "offset": "0x2D1C",
      "linear": "0x3D0AC",
      "nearOffset": "0x2D1C"
    },
    {
      "name": "_s_hitlerchase4",
      "segment": "0x3A39",
      "offset": "0x2D2C",
      "linear": "0x3D0BC",
      "nearOffset": "0x2D2C"
    },
    {
      "name": "_s_hitlerdeathcam",
      "segment": "0x3A39",
      "offset": "0x2D3C",
      "linear": "0x3D0CC",
      "nearOffset": "0x2D3C"
    },
    {
      "name": "_s_hitlerdie1",
      "segment": "0x3A39",
      "offset": "0x2D4C",
      "linear": "0x3D0DC",
      "nearOffset": "0x2D4C"
    },
    {
      "name": "_s_hitlerdie2",
      "segment": "0x3A39",
      "offset": "0x2D5C",
      "linear": "0x3D0EC",
      "nearOffset": "0x2D5C"
    },
    {
      "name": "_s_hitlerdie3",
      "segment": "0x3A39",
      "offset": "0x2D6C",
      "linear": "0x3D0FC",
      "nearOffset": "0x2D6C"
    },
    {
      "name": "_s_hitlerdie4",
      "segment": "0x3A39",
      "offset": "0x2D7C",
      "linear": "0x3D10C",
      "nearOffset": "0x2D7C"
    },
    {
      "name": "_s_hitlerdie5",
      "segment": "0x3A39",
      "offset": "0x2D8C",
      "linear": "0x3D11C",
      "nearOffset": "0x2D8C"
    },
    {
      "name": "_s_hitlerdie6",
      "segment": "0x3A39",
      "offset": "0x2D9C",
      "linear": "0x3D12C",
      "nearOffset": "0x2D9C"
    },
    {
      "name": "_s_hitlerdie7",
      "segment": "0x3A39",
      "offset": "0x2DAC",
      "linear": "0x3D13C",
      "nearOffset": "0x2DAC"
    },
    {
      "name": "_s_hitlerdie8",
      "segment": "0x3A39",
      "offset": "0x2DBC",
      "linear": "0x3D14C",
      "nearOffset": "0x2DBC"
    },
    {
      "name": "_s_hitlerdie9",
      "segment": "0x3A39",
      "offset": "0x2DCC",
      "linear": "0x3D15C",
      "nearOffset": "0x2DCC"
    },
    {
      "name": "_s_hitlerdie10",
      "segment": "0x3A39",
      "offset": "0x2DDC",
      "linear": "0x3D16C",
      "nearOffset": "0x2DDC"
    },
    {
      "name": "_s_hitlershoot1",
      "segment": "0x3A39",
      "offset": "0x2DEC",
      "linear": "0x3D17C",
      "nearOffset": "0x2DEC"
    },
    {
      "name": "_s_hitlershoot2",
      "segment": "0x3A39",
      "offset": "0x2DFC",
      "linear": "0x3D18C",
      "nearOffset": "0x2DFC"
    },
    {
      "name": "_s_hitlershoot3",
      "segment": "0x3A39",
      "offset": "0x2E0C",
      "linear": "0x3D19C",
      "nearOffset": "0x2E0C"
    },
    {
      "name": "_s_hitlershoot4",
      "segment": "0x3A39",
      "offset": "0x2E1C",
      "linear": "0x3D1AC",
      "nearOffset": "0x2E1C"
    },
    {
      "name": "_s_hitlershoot5",
      "segment": "0x3A39",
      "offset": "0x2E2C",
      "linear": "0x3D1BC",
      "nearOffset": "0x2E2C"
    },
    {
      "name": "_s_hitlershoot6",
      "segment": "0x3A39",
      "offset": "0x2E3C",
      "linear": "0x3D1CC",
      "nearOffset": "0x2E3C"
    },
    {
      "name": "_s_bjrun1",
      "segment": "0x3A39",
      "offset": "0x2E54",
      "linear": "0x3D1E4",
      "nearOffset": "0x2E54"
    },
    {
      "name": "_s_bjrun1s",
      "segment": "0x3A39",
      "offset": "0x2E64",
      "linear": "0x3D1F4",
      "nearOffset": "0x2E64"
    },
    {
      "name": "_s_bjrun2",
      "segment": "0x3A39",
      "offset": "0x2E74",
      "linear": "0x3D204",
      "nearOffset": "0x2E74"
    },
    {
      "name": "_s_bjrun3",
      "segment": "0x3A39",
      "offset": "0x2E84",
      "linear": "0x3D214",
      "nearOffset": "0x2E84"
    },
    {
      "name": "_s_bjrun3s",
      "segment": "0x3A39",
      "offset": "0x2E94",
      "linear": "0x3D224",
      "nearOffset": "0x2E94"
    },
    {
      "name": "_s_bjrun4",
      "segment": "0x3A39",
      "offset": "0x2EA4",
      "linear": "0x3D234",
      "nearOffset": "0x2EA4"
    },
    {
      "name": "_s_bjjump1",
      "segment": "0x3A39",
      "offset": "0x2EB4",
      "linear": "0x3D244",
      "nearOffset": "0x2EB4"
    },
    {
      "name": "_s_bjjump2",
      "segment": "0x3A39",
      "offset": "0x2EC4",
      "linear": "0x3D254",
      "nearOffset": "0x2EC4"
    },
    {
      "name": "_s_bjjump3",
      "segment": "0x3A39",
      "offset": "0x2ED4",
      "linear": "0x3D264",
      "nearOffset": "0x2ED4"
    },
    {
      "name": "_s_bjjump4",
      "segment": "0x3A39",
      "offset": "0x2EE4",
      "linear": "0x3D274",
      "nearOffset": "0x2EE4"
    },
    {
      "name": "_s_deathcam",
      "segment": "0x3A39",
      "offset": "0x2EF4",
      "linear": "0x3D284",
      "nearOffset": "0x2EF4"
    }
  ]
} as const;

export type DGroupLayout = typeof DGROUP_LAYOUT;
export type SaveRecordName = DGroupLayout["saveRecords"][number]["name"];
