/////////////////////////////////////////////////
//
// MUSE Header for .WL6
// Created Tue Jul 14 15:04:53 1992
//
/////////////////////////////////////////////////

export const NUMSOUNDS = 87;
export const NUMSNDCHUNKS = 288;

//
// Sound names & indexes
//
export enum soundnames {
		HITWALLSND = 0,              // 0
		SELECTWPNSND = 1,            // 1
		SELECTITEMSND = 2,           // 2
		HEARTBEATSND = 3,            // 3
		MOVEGUN2SND = 4,             // 4
		MOVEGUN1SND = 5,             // 5
		NOWAYSND = 6,                // 6
		NAZIHITPLAYERSND = 7,        // 7
		SCHABBSTHROWSND = 8,         // 8
		PLAYERDEATHSND = 9,          // 9
		DOGDEATHSND = 10,             // 10
		ATKGATLINGSND = 11,           // 11
		GETKEYSND = 12,               // 12
		NOITEMSND = 13,               // 13
		WALK1SND = 14,                // 14
		WALK2SND = 15,                // 15
		TAKEDAMAGESND = 16,           // 16
		GAMEOVERSND = 17,             // 17
		OPENDOORSND = 18,             // 18
		CLOSEDOORSND = 19,            // 19
		DONOTHINGSND = 20,            // 20
		HALTSND = 21,                 // 21
		DEATHSCREAM2SND = 22,         // 22
		ATKKNIFESND = 23,             // 23
		ATKPISTOLSND = 24,            // 24
		DEATHSCREAM3SND = 25,         // 25
		ATKMACHINEGUNSND = 26,        // 26
		HITENEMYSND = 27,             // 27
		SHOOTDOORSND = 28,            // 28
		DEATHSCREAM1SND = 29,         // 29
		GETMACHINESND = 30,           // 30
		GETAMMOSND = 31,              // 31
		SHOOTSND = 32,                // 32
		HEALTH1SND = 33,              // 33
		HEALTH2SND = 34,              // 34
		BONUS1SND = 35,               // 35
		BONUS2SND = 36,               // 36
		BONUS3SND = 37,               // 37
		GETGATLINGSND = 38,           // 38
		ESCPRESSEDSND = 39,           // 39
		LEVELDONESND = 40,            // 40
		DOGBARKSND = 41,              // 41
		ENDBONUS1SND = 42,            // 42
		ENDBONUS2SND = 43,            // 43
		BONUS1UPSND = 44,             // 44
		BONUS4SND = 45,               // 45
		PUSHWALLSND = 46,             // 46
		NOBONUSSND = 47,              // 47
		PERCENT100SND = 48,           // 48
		BOSSACTIVESND = 49,           // 49
		MUTTISND = 50,                // 50
		SCHUTZADSND = 51,             // 51
		AHHHGSND = 52,                // 52
		DIESND = 53,                  // 53
		EVASND = 54,                  // 54
		GUTENTAGSND = 55,             // 55
		LEBENSND = 56,                // 56
		SCHEISTSND = 57,              // 57
		NAZIFIRESND = 58,             // 58
		BOSSFIRESND = 59,             // 59
		SSFIRESND = 60,               // 60
		SLURPIESND = 61,              // 61
		TOT_HUNDSND = 62,             // 62
		MEINGOTTSND = 63,             // 63
		SCHABBSHASND = 64,            // 64
		HITLERHASND = 65,             // 65
		SPIONSND = 66,                // 66
		NEINSOVASSND = 67,            // 67
		DOGATTACKSND = 68,            // 68
		FLAMETHROWERSND = 69,         // 69
		MECHSTEPSND = 70,             // 70
		GOOBSSND = 71,                // 71
		YEAHSND = 72,                 // 72
		DEATHSCREAM4SND = 73,         // 73
		DEATHSCREAM5SND = 74,         // 74
		DEATHSCREAM6SND = 75,         // 75
		DEATHSCREAM7SND = 76,         // 76
		DEATHSCREAM8SND = 77,         // 77
		DEATHSCREAM9SND = 78,         // 78
		DONNERSND = 79,               // 79
		EINESND = 80,                 // 80
		ERLAUBENSND = 81,             // 81
		KEINSND = 82,                 // 82
		MEINSND = 83,                 // 83
		ROSESND = 84,                 // 84
		MISSILEFIRESND = 85,          // 85
		MISSILEHITSND = 86,           // 86
		LASTSOUND = 87
}

//
// Base offsets
//
export const STARTPCSOUNDS = 0;
export const STARTADLIBSOUNDS = 87;
export const STARTDIGISOUNDS = 174;
export const STARTMUSIC = 261;

//
// Music names & indexes
//
export enum musicnames {
		CORNER_MUS = 0,              // 0
		DUNGEON_MUS = 1,             // 1
		WARMARCH_MUS = 2,            // 2
		GETTHEM_MUS = 3,             // 3
		HEADACHE_MUS = 4,            // 4
		HITLWLTZ_MUS = 5,            // 5
		INTROCW3_MUS = 6,            // 6
		NAZI_NOR_MUS = 7,            // 7
		NAZI_OMI_MUS = 8,            // 8
		POW_MUS = 9,                 // 9
		SALUTE_MUS = 10,              // 10
		SEARCHN_MUS = 11,             // 11
		SUSPENSE_MUS = 12,            // 12
		VICTORS_MUS = 13,             // 13
		WONDERIN_MUS = 14,            // 14
		FUNKYOU_MUS = 15,             // 15
		ENDLEVEL_MUS = 16,            // 16
		GOINGAFT_MUS = 17,            // 17
		PREGNANT_MUS = 18,            // 18
		ULTIMATE_MUS = 19,            // 19
		NAZI_RAP_MUS = 20,            // 20
		ZEROHOUR_MUS = 21,            // 21
		TWELFTH_MUS = 22,             // 22
		ROSTER_MUS = 23,              // 23
		URAHERO_MUS = 24,             // 24
		VICMARCH_MUS = 25,            // 25
		PACMAN_MUS = 26,              // 26
		LASTMUSIC = 27
}

/////////////////////////////////////////////////
//
// Thanks for playing with MUSE!
//
/////////////////////////////////////////////////
