export const ENDSTR1 = "Heroes don't quit, but\ngo ahead and press Y\nif you aren't one.";
export const ENDSTR2 = "Press Y to quit,\nor press N to enjoy\nmore violent diversion.";
export const ENDSTR3 = "Depressing the Y key means\nyou must return to the\nhumdrum workday world.";
export const ENDSTR4 = "Hey, quit or play,\nY or N:\nit's your choice.";
export const ENDSTR5 = "Sure you don't want to\nwaste a few more\nproductive hours?";
export const ENDSTR6 = "I think you had better\nplay some more. Please\npress N...please?";
export const ENDSTR7 = "If you are tough, press N.\nIf not, press Y daintily.";
export const ENDSTR8 = "I'm thinkin' that\nyou might wanna press N\nto play more. You do it.";
export const ENDSTR9 = "Sure. Fine. Quit.\nSee if we care.\nGet it over with.\nPress Y.";

export const STR_ENDGAME1 = "We owe you a great debt, Mr. Blazkowicz.";
export const STR_ENDGAME2 = "You have served your country well.";
export const STR_ENDGAME3 = "With the spear gone, the Allies will finally";
export const STR_ENDGAME4 = "by able to destroy Hitler...";

export const STR_COPY1 = "That's close, but not close enough to get";
export const STR_COPY2 = "you into the game.";

export const STR_COPY3 = "Wow, you must have the early version of the";
export const STR_COPY4 = "manual with the totally false information in it.";

export const STR_COPY5 = "I would let you into the game, but seeing";
export const STR_COPY6 = "as that was not at all the right answer...";

export const STR_COPY7 = "It's just too bad we can't get together on";
export const STR_COPY8 = "this one.  Sorry.";

export const STR_COPY9 = "Hey, you're just SO off base!";

export const STR_COPY10 = "You know, I once typed that myself when";
export const STR_COPY11 = "I was your age.";

export const STR_COPY12 = "Nops.  Zero points.  Zugga.";

export const STR_COPY13 = "Yeah...right.";

export const STR_COPY14 = "You must like these quizzes.";

export const STR_COPY15 = "Could be called \"PixelMeister\"?";

export const STR_COPY16 = "Might engineer some software?";

export const STR_COPY17 = "Would be found";
export const STR_COPY18 = "directing creatively?";

export const STR_COPY19 = "Might be found";
export const STR_COPY20 = "handling operations?";

export const STR_COPY21 = "Has a name familiar";
export const STR_COPY22 = "to your weatherman?";

export const STR_NOPE1 = "Welcome to the DOS prompt, pirate!";
export const STR_NOPE2 = "Eat hot DOS prompt, goober!";
export const STR_NOPE3 = "Ya know, this program doesn't cost that much.";
export const STR_NOPE4 = "Hey...weren't you just AT this DOS prompt?";
export const STR_NOPE5 = "What's a nice user like you doin' at a DOS prompt like this?";
export const STR_NOPE6 = "Well, I'm sure you just \"misplaced\" the manual...";
export const STR_NOPE7 = "Run me again when you've boned up on your manual a bit.";
export const STR_NOPE8 = "Nice try, but no Spear.";
export const STR_NOPE9 = "That information is in the Spear of Destiny manual, by the way.";

export const STR_MISC1 = "Under \"Killing the Enemy\", what";
export const STR_MISC2 = "type of enemy is pictured?";

export const STR_MISC3 = "How many eyelets are on B.J.'s";
export const STR_MISC4 = "boots? (see page 2)";

export const STR_MISC5 = "The word \"minister\" appears in";
export const STR_MISC6 = "what gray shape on page 2?";

export const STR_MISC7 = "How many bullets does B.J. have";
export const STR_MISC8 = "on the screen-shot in the middle";
export const STR_MISC9 = "of page 9?";

export const STR_STAR = "star";
export const STR_DEBRIEF = " DEBRIEFING\n SESSION\n";
export const STR_ENEMY1 = "Name the member of the";
export const STR_ENEMY2 = "enemy forces shown above";

export const STR_CHECKMAN = "CHECK YER MANUAL!";
export const STR_MAN1 = "Which manual page";
export const STR_MAN2 = "is the Options Menu";
export const STR_MAN3 = "function";
export const STR_MAN4 = "on?";

export const STR_ID1 = "Which member of Id Software:";
