export const QUITSUR = "Are you sure you want\n" +
		"to quit this great game?";

export const CURGAME = "You are currently in\n" +
		"a game. Continuing will\n" +
		"erase old game. Ok?";

export const GAMESVD = "There's already a game\n" +
		"saved at this position.\n" +
		"      Overwrite?";

export const ENDGAMESTR = "Are you sure you want\n" +
					"to end the game you\n" +
					"are playing? (Y or N):";

export const STR_NG = "New Game";
export const STR_SD = "Sound";
export const STR_CL = "Control";
export const STR_LG = "Load Game";
export const STR_SG = "Save Game";
export const STR_CV = "Change View";
export const STR_VS = "View Scores";
export const STR_EG = "End Game";
export const STR_BD = "Back to Demo";
export const STR_QT = "Quit";

export const STR_LOADING = "Loading";
export const STR_SAVING = "Saving";

export const STR_GAME = "Game";
export const STR_DEMO = "Demo";
export const STR_LGC = "Load Game called\n\"";
export const STR_EMPTY = "empty";
export const STR_CALIB = "Calibrate";
export const STR_JOYST = "Joystick";
export const STR_MOVEJOY = "Move joystick to\nupper left and\npress button 0\n";
export const STR_MOVEJOY2 = "Move joystick to\nlower right and\npress button 1\n";
export const STR_ESCEXIT = "ESC to exit";

export const STR_NONE = "None";
export const STR_PC = "PC Speaker";
export const STR_ALSB = "AdLib/Sound Blaster";
export const STR_DISNEY = "Disney Sound Source";
export const STR_SB = "Sound Blaster";

export const STR_MOUSEEN = "Mouse Enabled";
export const STR_JOYEN = "Joystick Enabled";
export const STR_PORT2 = "Use joystick port 2";
export const STR_GAMEPAD = "Gravis GamePad Enabled";
export const STR_SENS = "Mouse Sensitivity";
export const STR_CUSTOM = "Customize controls";

export const STR_DADDY = "Can I play, Daddy?";
export const STR_HURTME = "Don't hurt me.";
export const STR_BRINGEM = "Bring 'em on!";
export const STR_DEATH = "I am Death incarnate!";

export const STR_MOUSEADJ = "Adjust Mouse Sensitivity";
export const STR_SLOW = "Slow";
export const STR_FAST = "Fast";

export const STR_CRUN = "Run";
export const STR_COPEN = "Open";
export const STR_CFIRE = "Fire";
export const STR_CSTRAFE = "Strafe";

export const STR_LEFT = "Left";
export const STR_RIGHT = "Right";
export const STR_FRWD = "Frwd";
export const STR_BKWD = "Bkwrd";
export const STR_THINK = "Thinking";

export const STR_SIZE1 = "Use arrows to size";
export const STR_SIZE2 = "ENTER to accept";
export const STR_SIZE3 = "ESC to cancel";

export const STR_YOUWIN = "you win!";

export const STR_TOTALTIME = "total time";

export const STR_RATKILL = "kill    %";
export const STR_RATSECRET = "secret    %";
export const STR_RATTREASURE = "treasure    %";

export const STR_BONUS = "bonus";
export const STR_TIME = "time";
export const STR_PAR = " par";

export const STR_RAT2KILL = "kill ratio    %";
export const STR_RAT2SECRET = "secret ratio    %";
export const STR_RAT2TREASURE = "treasure ratio    %";

export const STR_DEFEATED = "defeated!";

export const STR_CHEATER1 = "You now have 100% Health,";
export const STR_CHEATER2 = "99 Ammo and both Keys!";
export const STR_CHEATER3 = "Note that you have basically";
export const STR_CHEATER4 = "eliminated your chances of";
export const STR_CHEATER5 = "getting a high score!";

export const STR_NOSPACE1 = "There is not enough space";
export const STR_NOSPACE2 = "on your disk to Save Game!";

export const STR_SAVECHT1 = "Your Save Game file is,";
export const STR_SAVECHT2 = "shall we say, \"corrupted\".";
export const STR_SAVECHT3 = "But I'll let you go on and";
export const STR_SAVECHT4 = "play anyway....";

export const STR_SEEAGAIN = "Let's see that again!";
