//////////////////////////////////////
//
// Graphics .H file for .SOD
// IGRAB-ed on Fri Jul 31 18:31:00 1992
//
//////////////////////////////////////

export enum graphicnums {



	ENUMEND
}

//
// Data LUMPs
//

//
// Amount of each data item
//
export const NUMCHUNKS    = 414;
export const NUMFONT      = 0;
export const NUMFONTM     = 0;
export const NUMPICS      = 0;
export const NUMPICM      = 0;
export const NUMSPRITES   = 0;
export const NUMTILE8     = 0;
export const NUMTILE8M    = 0;
export const NUMTILE16    = 144;
export const NUMTILE16M   = 270;
export const NUMTILE32    = 0;
export const NUMTILE32M   = 0;
export const NUMEXTERNS   = 0;
//
// File offsets for data items
//
export const STARTFONT    = 0;
export const STARTFONTM   = 0;
export const STARTPICS    = 0;
export const STARTPICM    = 0;
export const STARTSPRITES = 0;
export const STARTTILE8   = 0;
export const STARTTILE8M  = 0;
export const STARTTILE16  = 0;
export const STARTTILE16M = 144;
export const STARTTILE32  = 414;
export const STARTTILE32M = 414;
export const STARTEXTERNS = 414;

//
// Thank you for using IGRAB!
//
