//////////////////////////////////////
//
// Graphics .H file for .WL1
// IGRAB-ed on Sat May 02 02:32:49 1992
//
//////////////////////////////////////

// typedef enum {
export enum graphicnums {
		// Lump Start
		H_BJPIC=3,
		H_CASTLEPIC=4,                 // 4
		H_KEYBOARDPIC=5,               // 5
		H_JOYPIC=6,                    // 6
		H_MOUSEPIC=7,                  // 7
		H_BOTHPIC=8,                   // 8
		H_GAMEPADPIC=9,                // 9
		H_HEALPIC=10,                  // 10
		H_TREASUREPIC=11,              // 11
		H_GUNPIC=12,                   // 12
		H_KEYPIC=13,                   // 13
		H_BLAZEPIC=14,                 // 14
		H_WEAPON1234PIC=15,            // 15
		H_WOLFLOGOPIC=16,              // 16
		H_VISAPIC=17,                  // 17
		H_MCPIC=18,                    // 18
		H_IDLOGOPIC=19,                // 19
		H_FAXPIC=20,                   // 20
		H_GALACTIXPIC=21,              // 21
		H_FGODMOMPIC=22,               // 22
		H_AUSTRALIAPIC=23,             // 23
		H_CANADAPIC=24,                // 24
		H_UKPIC=25,                    // 25
		H_TOPWINDOWPIC=26,             // 26
		H_LEFTWINDOWPIC=27,            // 27
		H_RIGHTWINDOWPIC=28,           // 28
		H_BOTTOMINFOPIC=29,            // 29
}
