export const QUITSUR = "Estas seguro que quieres\nparar este gran juego?";

export const CURGAME = "Ahora estas en\nun juego. Si continuas\nborras el juego viejo. O.K.?";

export const GAMESVD = "Ya hay un juego\nguardado en esta posicion.\nsobre-escribir?";

export const ENDGAMESTR = "Estas seguro que quieres\nterminar el juego que\nestas jugando?  (S  o  N):";

export const STR_NG = "Juego nuevo";
export const STR_SD = "Sonido";
export const STR_CL = "Control";
export const STR_LG = "Cargar juego";
export const STR_SG = "Guardar juego";
export const STR_CV = "Cambiar vista";
export const STR_VS = "Ver anotacion";
export const STR_EG = "Abandonar";
export const STR_BD = "Regresar al demo";
export const STR_QT = "Parar";

export const STR_LOADING = "Cargando";
export const STR_SAVING = "Guardando";

export const STR_GAME = "Regresar, jugar";
export const STR_DEMO = "Regresar al Demo";
export const STR_LGC = "Cargar juego llamado\n\"";
export const STR_EMPTY = "vacio";
export const STR_CALIB = "Calibrar";
export const STR_JOYST = "Joystick";
export const STR_MOVEJOY = "Mover joystick a\narriba izq y\noprimir boton 0\n";
export const STR_MOVEJOY2 = "Mover joystick a\nabajo derecha y\noprimir boton 1\n";
export const STR_ESCEXIT = "ESC para salir";
export const STR_NONE = "Ninguno";
export const STR_PC = "P.C. bocina";
export const STR_ALSB = "AdLib/Sound Blaster";
export const STR_DISNEY = "Disney Sound Source";
export const STR_SB = "Sound Blaster";

export const STR_MOUSEEN = "Raton activado";
export const STR_JOYEN = "Joystick activado";
export const STR_PORT2 = "Use joystick puerto 2";
export const STR_GAMEPAD = "Gravis Gamepad Activada";
export const STR_SENS = "Raton Sensibilidad";
export const STR_CUSTOM = "Modificar controles";
export const STR_DADDY = "Papi puedo jugar?";
export const STR_HURTME = "No me hieras.";
export const STR_BRINGEM = "­Echamelos!";
export const STR_DEATH = "La muerte encarnada";

export const STR_MOUSEADJ = "Raton ajustar sensibilidad";
export const STR_SLOW = "Lento";
export const STR_FAST = "Rapido";

export const STR_CRUN = "Corre";
export const STR_COPEN = "Abre";
export const STR_CFIRE = "Fuego";
export const STR_CSTRAFE = "Ametrallar";

export const STR_LEFT = "Izquierda";
export const STR_RIGHT = "Derecha";
export const STR_FRWD = "Adelante";
export const STR_BKWD = "Atras";
export const STR_THINK = "Pensando";

export const STR_SIZE1 = "Use flechas para ajustar";
export const STR_SIZE2 = "Enter para aceptar";
export const STR_SIZE3 = "Esc para cancelar";

export const STR_YOUWIN = "Tu ganas";

export const STR_TOTALTIME = "Tiempo total";

export const STR_RATKILL = "Muertes    %";
export const STR_RATSECRET = "Secreto    %";
export const STR_RATTREASURE = "Tesoros    %";

export const STR_BONUS = "Bono";
export const STR_TIME = "Tiempo";
export const STR_PAR = "Par";

export const STR_RAT2KILL = "Muertes    %"; // ratio = promedio
export const STR_RAT2SECRET = "Secreto    %";
export const STR_RAT2TREASURE = "Tesoros    %";

export const STR_DEFEATED = "Derrotado!";

export const STR_CHEATER1 = "Ahora tienes 100% salud";
export const STR_CHEATER2 = "99 balas y dos llaves";
export const STR_CHEATER3 = "Notar que has basicamente";
export const STR_CHEATER4 = "eliminado tus chances de";
export const STR_CHEATER5 = "obtener puntos altos";

export const STR_NOSPACE1 = "No hay suficiente espacio";
export const STR_NOSPACE2 = "en tu disco para guardar juego";

export const STR_SAVECHT1 = "Tu archivo para guardar juego es";
export const STR_SAVECHT2 = "diremos,\"corrupto\".";
export const STR_SAVECHT3 = "Pero te dire, sigue y";
export const STR_SAVECHT4 = "de todos modos juega";

export const STR_SEEAGAIN = "Veamos eso de nuevo";
