//#define SPEAR
//#define JAPAN
// #define GOODTIMES
export const GOODTIMES = true;
// #define ARTSEXTERN
export const ARTSEXTERN = true;
// #define DEMOSEXTERN
export const DEMOSEXTERN = true;
//#define MYPROFILE
//#define DEBCHECK
// #define CARMACIZED
export const CARMACIZED = true;
//#define UPLOAD

export const SPEAR = false;
export const JAPAN = false;
export const MYPROFILE = false;
export const DEBCHECK = false;
export const UPLOAD = false;
